### ISSUE TITLE
can't debug on macosx?

### ISSUE THREAD

**Issue by helyho** [go-lang-plugin-org/go-lang-idea-plugin#2828] opened 2016-11-15 05:25 UTC
- Plugin version (or commit hash): 0.12.1799
- IDE name and version: Intellij 2016.2.5
- Java version: 1.8
- OS name and version:  MAC osx

- What are you trying to do?
  debug go source file.

- What would you expect to happen?
  can stop on my breakpoint,but we can run this go source file

- What happens?
 when i click "Debug build test.go and run " then the window of console type out 
```shell
"/Users/xxxxx/Library/Application Support/IntelliJIdea2016.2/Go/lib/dlv/mac/dlv" --listen=localhost:62269 --headless=true exec "/private/var/folders/rd/vk_p8pzx59v8g4_zs3xmh2z80000gn/T/Build test.go and rungo" --
GOROOT=/usr/local/Cellar/go/1.7.3/libexec
GOPATH=/Users/xxxxx/Work/GO
/usr/local/Cellar/go/1.7.3/libexec/bin/go build -o "/private/var/folders/rd/vk_p8pzx59v8g4_zs3xmh2z80000gn/T/Build test.go and rungo" -gcflags "-N -l" /Users/xxxxx/Work/GO/test.go
could not launch process: could not get thread count

Process finished with exit code 1
```
i try to codesign :
```
 ~/Library/Application Support/IntelliJIdea2016.2/Go/lib/dlv/mac  codesign -fs gdb-cert ./dlv
```

but this still like this.

```go
package main

import "fmt"

func main() {
	fmt.Print("sss");  // by breakpoint here
}
```

**Comment by dlsniper** [comment] 2016-11-15 07:57
Hi, 


This is a problem in delve. 
I'll close this as a duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2810. Please watch that one. 
Thank you.

**Closed by dlsniper** 2016-11-15 07:57 UTC
