### ISSUE TITLE
Add auto-parenthesis blacklist for some functions.

### ISSUE THREAD

**Issue by vburenin** [go-lang-plugin-org/go-lang-idea-plugin#2389] opened 2016-03-15 01:05 UTC
I am actively using GoConvey framework for unit testing purposes.
Whey I type something like this: So(ts, ShouldEqual, 1)
IDE automatically adds parentheses that messes up a user flow like this: So(ts, ShouldEqual(), 1)

In most cases it is awesome behavior, but not in this case.

As as solution I would propose a blacklist of function names that should not be autocompleted by parentheses.

**Comment by dlsniper** [comment] 2016-03-15 18:59
I'll close this as a duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2324 (it's even related to GoConvey. Also I think it should be related to type inference for arguments as well, not just completion.

**Closed by dlsniper** 2016-03-15 18:59 UTC
Labels: completion
