### ISSUE TITLE
Vendor directory contents only partially recognized.

### ISSUE THREAD

**Issue by maniksurtani** [go-lang-plugin-org/go-lang-idea-plugin#2351] opened 2016-02-18 22:45 UTC
- Plugin version 0.10.1137
- IDE name and version: IntelliJ IDEA 15.0.3 (build #IU-143.1821)
- Java version: 1.8.0_40
- OS name and version: Mac OS X 10.11.2

- What are you trying to do?
 * Used `govendor` to move deps into `vendor`.
 * Symlinked `vendor` to `vendor/src` (`ln -s ../vendor src`)
 * Added `github.com/<ME>/<PROJ>/vendor` to project libraries in IDEA settings

- What would you expect to happen?
Libraries in `/vendor` are picked up and can be inspected as if they were in `$WORKSPACE/` 

- What happens?
Libraries *are* picked up. They even compile and run just fine. But the IDE cannot inspect functions on types declared in vendored libs.

Link to repo containing an example:

https://github.com/maniksurtani/intellij_go_plugin_test

Screenshot:

![screen shot 2016-02-18 at 2 37 03 pm](https://cloud.githubusercontent.com/assets/47146/13160742/2e5ccd96-d64e-11e5-96d1-7244823dd9ce.png)

**Comment by dlsniper** [comment] 2016-02-18 23:53
I've managed to replicate this on my IDE as well.
It is interesting that if instead of the symlink there's a directory `src` then everything works as intended.
I'm not sure if we want to consider this case or not for https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1820 or not.
Maybe this issue uncovers something else in the resolver?

@zolotov I'll leave this in your more capable hands.

**Comment by maniksurtani** [comment] 2016-02-19 00:13
Just to add to this, pls make sure you remove the libs from your GOPATH first, to make sure the IDE has to get them from `vendor/`.

Re: what the plugin sees, it is odd. The plugin *does* locate the lib src files correctly - you can even click through to them. It just doesn't autocomplete **some** functions. E.g., it sees `Upper()` in the `cases` package, but not the return value of `Upper()`, which is a `cases.Caser`, and hence not the functions on `cases.Caser` like `String()`.

**Comment by tnine** [comment] 2016-02-22 03:43
I'm also experiencing this when using vendoring with glide.  If you download this sha of my project, it also reproduces the issue.

https://github.com/30x/shipyard/tree/c6b4d05f01b6d1f566878f43dae780e57f4539aa/shipyard

**Comment by horkhe** [comment] 2016-03-07 22:14
Just wanted to note that with GoLang 1.6 release that enabled vendoring support by default, the priority of this issue has increased. And it would be nice to avoid hacks like creating `vendor/src` symlink.

**Comment by dlsniper** [comment] 2016-03-07 22:16
I'll close this in favor of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1820

**Closed by dlsniper** 2016-03-07 22:16 UTC
Labels: resolving

**Comment by chrisolsen** [comment] 2016-03-20 16:37
I am still seeing this issue using the v0.11.1203 nightly build. According to #1820 this issue should be solved, but as noted in this bug report's title there is still only partial recognition of vendor contents for me. Is anyone else still having problems with this?  I have had to move back to vim for now due to the large number of red flags throughout my project.

**Comment by dlsniper** [comment] 2016-03-20 16:40
@chrisolsen please open a separate issue and describe there what the project layout is and how the project is configured. This issue is before those changes and it might not be that they are similar. Thank you.

**Comment by florinutz** [comment] 2018-06-19 14:00
still seeing this
