### ISSUE TITLE
Unresolved type error when dereferencing struct field containing function pointer

### ISSUE THREAD

**Issue by drathier** [go-lang-plugin-org/go-lang-idea-plugin#2278] opened 2016-01-21 18:10 UTC
type subFunc struct {
    	f *func(event interface{})
    }
    
    func (s subFunc) When(event interface{}) {
    	(*s.f)(event)
    }

I get "Unresolved type 's'` error on this code in win10. PyCharm 4.5.4 with go plugin 0.9.1025, go1.5.1. It compiles just fine. Adding another pair of parenthesis around `s.f` to get `(*(s.f))(event)` does not fix the problem.

**Comment by dlsniper** [comment] 2016-01-21 18:16
@ignatov this looks like a duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2259 imho

**Comment by ignatov** [comment] 2016-01-21 21:07
Thanks for reporting.

**Comment by ignatov** [comment] 2016-01-23 21:09
Duplicates #2259.

**Closed by ignatov** 2016-01-23 21:09 UTC
Labels: resolving
