### ISSUE TITLE
Wrong if expression parsing

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1509] opened 2015-03-31 16:53 UTC
```go
package main

func test() []byte {
	if err := []byte("123"); err != nil { // <element> or '{' expected, got 'return'
		return err
	}

	return nil
}

func main () {
	test();
}
```

**Comment by dlsniper** [comment] 2015-03-31 16:54
Closing as duplicate of previous ticket #1494

**Closed by dlsniper** 2015-03-31 16:54 UTC
