### ISSUE TITLE
[1.0] Redeclare type method inspection

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1373] opened 2015-02-25 08:31 UTC
```go
type Message byte

func (m *Message) Foo() {
}

func (m Message) Foo() {
}

func (m Message) Foo() string {
    return ""
}
```

**Comment by dlsniper** [comment] 2015-02-25 08:33
Closing as duplicate of #1023

**Closed by dlsniper** 2015-02-25 08:33 UTC

**Comment by linniksa** [comment] 2015-02-25 08:37
ah, sorry

**Comment by dlsniper** [comment] 2015-02-25 08:38
Don't worry ;)
