### ISSUE TITLE
Support GCC compiling

### ISSUE THREAD

**Issue by nikoldavis** [go-lang-plugin-org/go-lang-idea-plugin#616] opened 2014-02-16 22:23 UTC
I can't run or build and go files from within IntelliJ, my details are as follows:

I am running IntelliJ 13.0.2

 1. When I build I get the following error:

----
    /usr/local/go/bin/go build  -o /Users/samirarabbanian/git/go_helloworld/go_helloworld /Users/samirarabbanian/git/go_helloworld/src/go_helloworld.go

    Could't build project /Users/samirarabbanian/git/go_helloworld/go_helloworld
     command-line-arguments
    exec gcc: No such file or directory
    /usr/local/go/pkg/tool/darwin_amd64/6l: running gcc failed: unsuccessful exit status 0x100
----

 2. When I run I get the the following error:

----
    /usr/local/go/bin/go run /Users/samirarabbanian/git/go_helloworld/src/go_helloworld.go
     command-line-arguments 
    exec gcc: No such file or directory
    /usr/local/go/pkg/tool/darwin_amd64/6l: running gcc failed: unsuccessful exit status 0x100

    Process finished with exit code 2
----

An identical configuration works correct on the computer next to me.

When I run either of these command from the command line it works correctly.

I have the following /etc/launchctl.conf configuration (same as the computer next to me):

    setenv PATH ${GOPATH//://bin:}/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

    setenv GOROOT /usr/local/go
    setenv GOPATH /usr/local/go_path

When I run go env I get the following output:

    GOARCH="amd64"
    GOBIN=""
    GOCHAR="6"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="darwin"
    GOOS="darwin"
    GOPATH="/usr/local/go_path"
    GORACE=""
    GOROOT="/usr/local/go"
    GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
    TERM="dumb"
    CC="clang"
    GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fno-common"
    CXX="clang++"
    CGO_ENABLED="1"

**Comment by dlsniper** [comment] 2015-02-12 15:01
@ignatov I've moved this to 1.maybe as I'm not sure if the plugin should support gcc compile from 1.0 or we should add it after.

**Comment by dlsniper** [comment] 2015-11-03 22:09
Duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/543 I guess I still need to check if this happens or not but I need to install gccgo for this.

**Closed by dlsniper** 2015-11-03 22:09 UTC
Labels: features
