### ISSUE TITLE
Can't create Go project in WebStorm 10-alpha

### ISSUE THREAD

**Issue by dvshapkin** [go-lang-plugin-org/go-lang-idea-plugin#1396] opened 2015-02-28 14:29 UTC
When creating a new project, the project list does not contain the Go project

**Comment by dlsniper** [comment] 2015-02-28 14:44
Closing as duplicate of #1347

**Closed by dlsniper** 2015-02-28 14:44 UTC

**Comment by dvshapkin** [comment] 2015-03-02 04:36
![image](https://cloud.githubusercontent.com/assets/6525348/6435418/55cb2394-c0d0-11e4-827e-068e314ab089.png)

**Comment by dlsniper** [comment] 2015-03-02 08:51
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1398#issuecomment-76676463
