### ISSUE TITLE
error message for multi args.

### ISSUE THREAD

**Issue by jayunit100** [go-lang-plugin-org/go-lang-idea-plugin#1364] opened 2015-02-23 22:10 UTC
I've found an apparent inconsistency of the alpha release candidate (Go.92.zip
) and the latest Go package (1.4.2), regarding interfaces and var args, for the following methods
```Go
   //wants a 2nd arg. for func String(reply interface{}, err error) (string, error) {
    world, err := redis.String(c.Do("GET", "message1"))
```
The details are here. http://stackoverflow.com/questions/28684449/why-is-this-go-lang-intellij-plugin-is-inconsistent-with-gos-syntax ... hope this is useful (and not just a go mistake im making).

**Comment by dlsniper** [comment] 2015-02-23 22:14
Hi, 

It's not a mistake you are making, it's a known problem of the plugin.

This is a duplicate of 1352, #1343 or #1222. Please watch those for when this is fixed.

Thank you.

**Closed by dlsniper** 2015-02-23 22:14 UTC
