### ISSUE TITLE
Add Go SDK: The selected directory is not a valid home for Go SDK

### ISSUE THREAD

**Issue by johnleegrant** [go-lang-plugin-org/go-lang-idea-plugin#1502] opened 2015-03-30 15:11 UTC
Can't set Go SDK. 

Project Structure > SDKs > Add New SDK - Go SDK >
Browse to c:\go or c:\go\bin click OK and get the same error:
The selected directory is not a valid home for Go SDK

Windows 8.1
go version go1.4.2 windows/amd64
IntelliJ IDEA 14.1
Go Plugin 0.9.234
GOPATH=C:\Projects\Go

**Comment by johnleegrant** [comment] 2015-03-30 15:42
Now able to set the Go SDK. Was able to revert back to Go Plugin 0.9.223 via the alpha repository at https://plugins.jetbrains.com/plugins/alpha/list

**Comment by zolotov** [comment] 2015-03-30 15:58
Unfortunately I don't have windows. I will appreciate if you will able to debug this (https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/sdk/GoSdkType.java#L66). 

For now IDE checks that the path doesn't end with '/goroot', contains './bin/go' and has `./src/pkg/runtime/zversion.go` or `./src/runtime/zversion.go` file with version. Is something wrong with that for windows installation?

**Comment by linniksa** [comment] 2015-03-30 17:10
./bin/go.exe ?

**Comment by zolotov** [comment] 2015-03-30 17:24
@linniksa thanks! We definitely need committer with windows. Will be fixed in the closest nightly.

**Closed by zolotov** 2015-03-30 17:24 UTC

**Comment by mcandre** [comment] 2017-02-08 16:59
Same issue when attempting to configure GOROOT on macOS Sierra: For some reason, Gogland rejects `/Users/apennebaker/go` as my GOROOT. Wtf.

**Comment by zolotov** [comment] 2017-02-09 11:30
@mcandre how did you download/install GOROOT there?

**Comment by dlsniper** [comment] 2017-02-09 11:45
@zolotov that comment is a duplicate of: https://youtrack.jetbrains.com/issue/GO-3466

**Comment by hp18pixels** [comment] 2018-04-06 06:56
I solved it from here
[http://www.blog.teamguru.in/2018/04/06/selected-directory-is-not-a-valid-home-for-sdk/](http://www.blog.teamguru.in/2018/04/06/selected-directory-is-not-a-valid-home-for-sdk/)

1- Just close current error window and let run the android studio
2- open sdk manager as shown in below

3- Clik on Edit sdk location as below

4- Simply press next button if there is correct location for sdk you want to install there

5- let it be downloaded

6- install platform and SDK tools and  

7- Enjoy
