### ISSUE TITLE
Type inspection stopped working

### ISSUE THREAD

**Issue by bictorman** [go-lang-plugin-org/go-lang-idea-plugin#1977] opened 2015-11-08 14:58 UTC
![screencap](http://ipfs.pics/ipfs/QmXQ8qarpePbLXXsdw5ycxaYoKoA22bXPnQKJ56RNtH729?dl=1)
![go](http://ipfs.pics/ipfs/QmSo9Ba37rPAXehu6Awtp58NP3K6Tv4nJ1GmVEcWZ5pZ92?dl=1)
![idea](http://ipfs.pics/ipfs/Qmb3SdQq9tioA75QL5Wqi3nnDBpgcHDvyBPgLBvTUo5Z6m?dl=1)

Mac OS 10.9.5
Nothing on the event log.
No idea if it stopped working after the 0.9.610 update or randomly later.
Other inspections still work:

![screencap2](http://ipfs.pics/ipfs/QmQqUs1MyDicQHS9uuddf1CwKmkMjBoXdArkV4uVBRhJPv?dl=1)

**Comment by gondor** [comment] 2015-11-08 16:08
I'm also seeing this and **have the same versions as reported**.  It's also occurring on calls made to libraries via imports.  The imports resolve but the calls to functions within an import are unresolvable.  Worked perfect before the previous version.

**Comment by bictorman** [comment] 2015-11-08 16:58
Upgraded to IDEA 15 with plugin version 0.10.619, the issue persists.

**Comment by dlsniper** [comment] 2015-11-08 21:07
Hi, 

Can you please try to be more specific? I've just used the same build as 0.10.609 and I can't reproduce any errors with. Also type inference is not supported yet in the sense that the plugin can't distinguish between passing an int or a string as an argument to a function which expects a float.
Also there's no type checking for assigning different types between them when it comes to structs or otherwise and so on ( a few examples can be found here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/labels/type%20inference )

Thank you.

@ignatov Should this rather be closed unless something very clear comes up from feedback as type inference is known to be missing plugin wide and this doesn't bring anything new to the issue?

**Comment by bictorman** [comment] 2015-11-08 21:18
Really? I could have sworn that `var a string = 10`  was an error before, if it's a known limitation by all means close this.

**Comment by dlsniper** [comment] 2015-11-08 21:28
This was done with the same commit hash as the 609 release: ![snapshot128](https://cloud.githubusercontent.com/assets/607868/11022776/eb4a3be6-8667-11e5-9083-18a5c49db103.png) that's why I was asking for more accurate feedback as I can't find anything different in the behavior. Thank you.

**Comment by dlsniper** [comment] 2015-12-20 18:39
I'll close this for now.

**Closed by dlsniper** 2015-12-20 18:39 UTC
Labels: feedback required
