### ISSUE TITLE
too many arguments in call to...

### ISSUE THREAD

**Issue by jakecoffman** [go-lang-plugin-org/go-lang-idea-plugin#1369] opened 2015-02-24 19:08 UTC
Using the latest on 1.0.0alpha branch. 

You might be able to simplify this example more.

```go
package main

import (
	"fmt"
)

func main() {
	c := Parent{&Child{}, impl{}}
	c.Get("A", 1) // too many arguments in call to c.Get
	return
}

type Parent struct {
	*Child
	Interface
}

type Child struct {
	Unimplemented
}

type Interface interface {
	Get(string, ...int)
}

type impl struct{}

func (r impl) Get(s string, h ...int) {
	fmt.Println("HERE")
}

type Unimplemented interface {
	Get(s string)
}

```

**Comment by dlsniper** [comment] 2015-02-24 19:21
@zolotov I'm not sure this is a duplicate of #1343 or not (or if @ignatov should be assigned to this and not you :D)

**Closed** 2015-02-25 09:59 UTC
