### ISSUE TITLE
Switching between apps cause cursor to move from currently typing location

### ISSUE THREAD

**Issue by ajaysharma2007** [go-lang-plugin-org/go-lang-idea-plugin#1431] opened 2015-03-12 19:01 UTC
Hi,
   Switching between apps cause cursor to move from currently typing location.

   For  exmaple:
    type: 
var (
		
	)

    Switch app and come back. 
    
    var ()

**Comment by dlsniper** [comment] 2015-03-12 19:23
@ajaysharma2007 can you please read the readme and report more in the issue, like idea version, plugin version and so on? Until then I'll close the issue as it doesn't have enough details to even try to reproduce. Thank you.

**Closed by dlsniper** 2015-03-12 19:23 UTC

**Comment by ajaysharma2007** [comment] 2015-03-12 19:49
HI,
   Please find env details below:
    IDEA version: 14.0.3
   JAVA SDK version: 1.8
   Go plugin version: 0.9.16-dev
   Go SDK version 1.4.2

![before_switching](https://cloud.githubusercontent.com/assets/4421186/6626685/032b13c2-c8b6-11e4-8ca8-74952f32da3f.png)
![after_switching](https://cloud.githubusercontent.com/assets/4421186/6626687/05e19640-c8b6-11e4-857d-6cea7df744a5.png)

**Comment by zolotov** [comment] 2015-03-12 20:03
@dlsniper btw this is one of the reason why I don't like the idea of invoking go fmt on save :)

**Comment by dlsniper** [comment] 2015-03-12 21:35
I'll ping you on Gitter tomorrow, sorry for the on-off availability

**Comment by zolotov** [comment] 2015-03-12 21:51
It's ok, as you see I also don't make plugin regularly

**Comment by ajaysharma2007** [comment] 2015-03-12 23:19
@dlsniper @zolotov can you guys please open this again so that it's not lost. Thanks in advance.

**Comment by dlsniper** [comment] 2015-03-13 00:08
@ajaysharma2007 there's no real problem as far as I can tell, the plugin works as intended.
In the plugin configuration you'd see there's an option to run gofmt on save, selecting do nothing would prevent gofmt to work.
Regardless, please upgrade to the latest version as there we don't have the option to run gofmt / goimports on save yet
