### ISSUE TITLE
Compilation error: Can't load package: package .

### ISSUE THREAD

**Issue by dawi** [go-lang-plugin-org/go-lang-idea-plugin#1288] opened 2015-02-11 07:01 UTC
I get the following error whenever I try to compile a go program using the IDEA compile button:

> Information:11.02.15 07:45 - Compilation completed with 1 error and 0 warnings in 2 sec
> Error:go: can't load package: package .: no buildable Go source files in /Users/dawi/development/github/dawi/go-playground

In fact the only run configuration that works somehow is the "Go Single File" run configuration.
In tests, for example I get the same error.

Environment:
* OSX 10.10.2
* IntelliJ IDEA 14.0.3
* go-lang-idea-plugin 1.0.0.alpha#58
* go 1.4.1 (I tested with both hombrew and go-installer)

Other infos:
* Code completition and syntax highlighting are fine.
* Setting of GOPATH does not have an effect on this issue.
* It already occurs in a simple one file hello world application.

**Comment by dlsniper** [comment] 2015-02-11 07:19
I believe this is a duplicate of #1209 or #1210 and as noted in the release notes, this is a known problem. Thank you for reporting

**Closed by dlsniper** 2015-02-11 07:19 UTC

**Comment by alecswan** [comment] 2015-03-18 03:11
I am experiencing the same problem with the same system configuration and alpha#176 version of the plugin. Both issues #1209 and #1210 have been closed, but the problem persists. Are there any plans for fixing this?

**Comment by zolotov** [comment] 2015-03-18 07:38
@alecswan what exactly does persist? Both issues are actually fixed.

**Comment by alecswan** [comment] 2015-03-18 15:00
I am getting the following error when compiling my Go project in IntelliJ:
````
Information:3/18/15, 8:53 AM - Compilation completed with 1 error and 0 warnings in 0 sec
Error:go: can't load package: package .: no buildable Go source files in /Users/alebedev/Documents/dev/playground/go
````

The root of my Go project is in $GOPATH. The structure of the project is as follows:
go
  - src
    - pkg1
      - common
        - common.go
      - implementations
        - impl.go

My system configuration:
* OSX 10.9.5
* IntelliJ IDEA 14.0.3
* go-lang-idea-plugin 1.0.0.alpha#176 (installed as an entire ZIP)
* go 1.4.2 (installed with go-installer)

I first installed the plugin via IntelliJ repo, but then I uninstalled it and installed alpha#176 from disk as a ZIP.

**Comment by zolotov** [comment] 2015-03-18 15:26
> The root of my Go project is in $GOPATH.

So is it presented in File | Settings | Languages & Frameworks | Go Libraries? If not then just add it there.

**Comment by alecswan** [comment] 2015-03-18 15:36
In File | Other Settings | Default Settings | Languages & Frameworks | Go Libraries I already had the following entry: [GOPATH] /Users/alebedev/Documents/dev/playground/go/src. The entry is greyed out and I am unable to delete it. Note that it has /src at the end. My $GOPATH env variable is pointing to the directory containing /src. However, as I said, I am unable to delete this greyed out entry.

I added another entry /Users/alebedev/Documents/dev/playground/go, but that didn't solve the problem.

Any other ideas?

**Comment by zolotov** [comment] 2015-03-18 16:09
Other idea: since you have appropriate GOPATH variable in env try to run go build from command line.

**Comment by alecswan** [comment] 2015-03-18 17:30
Here is the trace from building Go files from $GOPATH:
```
go build -v -a ...
cmd/internal/rsc.io/arm/armasm
cmd/internal/rsc.io/x86/x86asm
funswan/pascal-triangle/common
funswan/pascal-triangle/implementations
cmd/internal/objfile
cmd/addr2line
cmd/nm
cmd/objdump
cmd/pprof
```

**Comment by zolotov** [comment] 2015-03-18 19:03
> go build -v -a 

IDEA doesn't run `go build` in such way. What the whole `go build` command that you use for compiling and what the command line that IDEA runs?

**Comment by alecswan** [comment] 2015-03-18 19:58
I don't know how to tell which command IntelliJ is running. However, when I run ```go build``` in $GOPATH I get the same error as in IntelliJ ```can't load package: package .: no buildable Go source files in /Users/alebedev/Documents/dev/playground/go```.

**Comment by zolotov** [comment] 2015-03-18 20:06
> I don't know how to tell which command IntelliJ is running. 

It is shown in the very first line of output.

> However, when I run go build in $GOPATH I get the same error as in IntelliJ can't load package: package .: no buildable Go source files in /Users/alebedev/Documents/dev/playground/go.

I see. Then just change working directory in run configuration

**Comment by alecswan** [comment] 2015-03-18 20:21
I pasted both lines from IntelliJ output:
```Information:3/18/15, 1:52 PM - Compilation completed with 1 error and 0 warnings in 1 sec
Error:go: can't load package: package .: no buildable Go source files in /Users/alebedev/Documents/dev/playground/go```

I don't understand why I need to change "run configuration" if I am only trying to compile (not run) the project.

**Comment by zolotov** [comment] 2015-03-18 20:26
> I don't understand why I need to change "run configuration" if I am only trying to compile (not run) the project.

What does it mean? What exactly are you doing inside IDE?

**Comment by alecswan** [comment] 2015-03-18 20:37
Build | Rebuild Project

**Comment by zolotov** [comment] 2015-03-18 20:41
Build | Rebuild Project is disabled for go (see #1453 for details). Are you sure about 1.0.0.alpha#176 version? Could you attach logs (Help | Show Log).

**Comment by alecswan** [comment] 2015-03-18 22:45
I was able to create a Run Configuration for my test class and run it. I guess I expected Build | Rebuild Project to work. I uninstalled Go plugin, restarted IntelliJ and installed it using the ZIP file again. Yet, still I am getting the same error during project rebuild.

I see the following message in idea.log related to the Go plugin:
```2015-03-18 16:44:08,075 [  27618]   INFO - t.GoModuleLibrariesInitializer - The directory is child of project root, skipping: /Users/alebedev/Documents/dev/playground/go/src ```

**Comment by zolotov** [comment] 2015-03-18 23:51
> I was able to create a Run Configuration for my test class and run it.

Glad to hear.

> I expected Build | Rebuild Project to work.

As you can see in #1453 discussion it's a big question what Rebuild Project should do in terms of `go build`

> I see the following message in idea.log related to the Go plugin:

Please attach full log
