### ISSUE TITLE
Compile and Debug

### ISSUE THREAD

**Issue by mvbaffa** [go-lang-plugin-org/go-lang-idea-plugin#1645] opened 2015-05-24 23:45 UTC
I have just installed Go Eclipe in Intellij Idea 14.1.3.

The main.go is running in the IDE but when I try to find the exe, after the Make, I clould not find it. My is GoPATH=GoApps.

If I run "go install HelloIdea" the exe is generated in the GoApps/bin directory. 

What are the configurations I must set to have my exe generated ?

When I try to create a Debug configuration it is asking for application executable. I have generated the exe with "go install" and I have have created a configuration like this:

![image](https://cloud.githubusercontent.com/assets/1565670/7790205/145a349c-0255-11e5-9b27-194b89af591c.png)

Whan I start the debug nothing happens:

![image](https://cloud.githubusercontent.com/assets/1565670/7790208/34d27572-0255-11e5-8bc8-8a096f8f5e05.png)

Must I use the GDB Console ? I do not know how.

How can I make it work ?

Thanks

**Comment by dlsniper** [comment] 2015-05-24 23:57
Hi @mvbaffa.

> I have just installed Go Eclipe in Intellij Idea 14.1.3.

This plugin has nothing to do with Eclipse, it's dedicated for IntelliJ platform :)

> What are the configurations I must set to have my exe generated ?

If you want to build a binary you can run the ```Go Application``` run configuration. I've seen in the screenshots you've provided that there's already a configuration for that.

> Whan I start the debug nothing happens:
> Must I use the GDB Console ? I do not know how.
> How can I make it work ?

You normally shouldn't use GDB console, it's there for power users and debugging purposes only.

Why you don't get anything in the debugging information area is because most likely the output from GDB isn't compatible with what the plugin understands. Also, the plugin support for GDB is experimental at the moment so don't count on it. 

Also, GDB support itself doesn't work properly with go, please see the official documentation: https://golang.org/doc/gdb 

> GDB does not understand Go programs well. [...]
> In time, a more Go-centric debugging architecture may be required.

Once GDB will properly support Go, chances are that the support within the plugin will improve.

Hope this helps.

P.S.
I'll close the thread as it's a duplicate of others already existing on the same theme.

**Closed by dlsniper** 2015-05-24 23:57 UTC

**Comment by mvbaffa** [comment] 2015-05-25 12:01
Of course GoClipse has nothing to do with Intellij. Which I prefer. Sorry

"If you want to build a binary you can run the Go Application run configuration. I've seen in the screenshots you've provided that there's already a configuration for that."

When I run the application using the configration i gave you I could not find any HelloIdea.exe. My directory Structure is the one suggested by the Go site (http://golang.org/doc/code.html) in the Go Workspaces section

D:\GoApps
   bin
   pkg
   src\
     HelloIdea/
       main.go

When I run the "go install HelloIdea", using the cmd, the HelloIdea.exe is generated into D:\GoApps\bin. But whan I run from Intellij the terminal shows me the program running correctly bu no "exe" is generated. At least it is not generated in the D:\GoApps\bin.

If GDB does not work properly. How can we debug the application. Is there another way ?

Thanks

**Comment by dlsniper** [comment] 2015-05-25 12:26
Currently Go Application runner will produce a binary in the temporary folder and it will ignore the -o switch if that's present in the custom go tool parameters, I'll submit a PR for that later on.

As for 
> If GDB does not work properly. How can we debug the application. Is there another way ?

As you can see from the go documentation, the problem is the Go runtime not being understood by GDB. There are a few attempts to get a form of debugging running but I'd say that neither is production ready. The closest one to a GDB-like behavior is [delve](https://github.com/derekparker/delve).

In my day to day work, I'm using fmt.Printf, log.Printf and panic(), to debug issues and tests, ofc. You can also have a reference for how other people debug go apps by reading either this: http://www.reddit.com/r/golang/comments/373f2s/whats_the_best_debugger_to_use_with_golang/ or the go mailing list https://groups.google.com/forum/#!searchin/golang-nuts/debug You could also ask there how other people debug their apps.

Hope this helps.

**Comment by mvbaffa** [comment] 2015-05-25 12:30
Ok 

Debugging with Printf, if this is the way, lets go with it.

Thanks
