### ISSUE TITLE
Unable to use step into in the debugger / Debugger Freezing

### ISSUE THREAD

**Issue by PatrickLaban** [go-lang-plugin-org/go-lang-idea-plugin#2185] opened 2015-12-28 04:54 UTC
* Plugin Version - 0.10.960
* IDEA - PyCharm 5.0.3 Professional
* JAVA - 1.7.0_91, OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1), OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
* Code example - [http://play.golang.org/p/GDQCFi8dgn](http://play.golang.org/p/GDQCFi8dgn)
* When attempting to use the step into command from line number 8 the debugger continues to loop back to line 8 without executing or stepping into the changeMe function.  Also if I press the step to next line once it highlights line 12 and displays the values for z.  When I press it a second time from there the debugger seems to freeze and displays the message "Connected to localhost/127.0.0.1:53079" under variables.

**Comment by ignatov** [comment] 2015-12-28 07:15
Please try to reproduce the issue from the command line.

**Comment by dlsniper** [comment] 2015-12-28 22:35
I've tested this on my setup via command line both with the bundled version and the latest in delve master and it looks like a delve issue. I've created the corresponding issue there.

**Comment by PatrickLaban** [comment] 2015-12-29 00:24
Thanks for testing this Florin.  I'm new to Go and haven't  used command line debugging with it.

**Comment by dlsniper** [comment] 2016-02-18 17:32
This was just closed on delve side. (Just to keep track of states)

**Comment by dlsniper** [comment] 2016-04-20 09:12
This was fixed in delve. Please reopen if needed.

**Closed by dlsniper** 2016-04-20 09:12 UTC
Labels: debugger, depends on 3rd party

**Comment by aniketgm** [comment] 2018-04-06 12:42
> This was just closed on delve side. (Just to keep track of states)
How was it done? Any solution link please. Thanks.

**Comment by dlsniper** [comment] 2018-04-06 12:55
> How was it done? Any solution link please. Thanks.

@aniketmeshram, the solution is linked above.

You can use the latest version of [GoLand IDE](https://jetbrains.com/go) or IntelliJ IDEA Ultimate with the Go plugin and this will work automatically.
