### ISSUE TITLE
Autocomplete not shows the methods of a struct from another file as argument of a function

### ISSUE THREAD

**Issue by dashaus** [go-lang-plugin-org/go-lang-idea-plugin#1437] opened 2015-03-14 21:37 UTC
```go
package main

// file context.go

type Context struct {
    Errors []string
}

func (c Context) redirect() {
}
```

```go
package main

// file main.go

func hello(c Context){
    c. // only show the "Errors" field but not the redirect method
}
```

**Comment by ignatov** [comment] 2015-03-15 07:40
Are those files placed in the same directory?

**Comment by linniksa** [comment] 2015-03-15 09:24
this happens if directory (/m on you screenshot) marked as project library

**Comment by zolotov** [comment] 2015-03-16 10:02
So, /m is inside project but marked as a project library?

**Comment by linniksa** [comment] 2015-03-16 10:06
yes... "/m" is just example for @ignatov screenshot

**Comment by zolotov** [comment] 2015-03-16 10:20
I don't know whether it's related to the issue but no one directory inside project should be marked as library. Please enable debug logging for `GoModuleLibrariesInitializer` (add `#com.goide.project.GoModuleLibrariesInitializer` in Help | Configure Debug Log Settings...), restart IDE and attach logs.

**Comment by linniksa** [comment] 2015-03-16 10:24
I did it by my self, because i use per-project GOPATH:
![default](https://cloud.githubusercontent.com/assets/424343/6664326/bafcc820-cbdf-11e4-9833-9e8543c7cf47.png)

**Comment by zolotov** [comment] 2015-03-16 11:06
I understand that, but there is a code that prevents marking directories in project as libraries and it seems it failed, so I need log to understand why it happened.

**Comment by linniksa** [comment] 2015-03-16 13:04
http://pastebin.com/i66YNptj

**Comment by dashaus** [comment] 2015-03-16 20:06
The error happens only when the project is inside of $GOPATH root.

**Comment by zolotov** [comment] 2015-03-16 23:58
Can't recreate. According to logs `Z:/go/apps/upay/src` is not marked as library, could you attach screenshot of Project View panel with expanded `External libraries` node?

My test project works fine with described configuration:

https://www.dropbox.com/s/ko52ijpb8pmnxhv/Screenshot%202015-03-17%2000.57.54.png?dl=0
https://www.dropbox.com/s/28esxhrx75e906x/Screenshot%202015-03-17%2000.58.00.png?dl=0

**Comment by dashaus** [comment] 2015-03-17 03:28
![preferences](https://cloud.githubusercontent.com/assets/1870208/6680880/4dd97920-cc55-11e4-980e-a38f51d13c1f.png)

The project must be in the $GOPATH path. If the project is not in the $GOPATH path it works well.

**Comment by dashaus** [comment] 2015-03-17 03:29
@zolov try to put your externalGo project inside of /Users/zolotov/tmp/gopath/src and you should see the error

**Comment by zolotov** [comment] 2015-03-17 08:03
I've reproduced it, thanks

**Closed** 2015-03-17 10:16 UTC
Labels: completion
