### ISSUE TITLE
String variable has been trimmed in Debug mode

### ISSUE THREAD

**Issue by scozv** [go-lang-plugin-org/go-lang-idea-plugin#2788] opened 2016-09-30 06:44 UTC
- Plugin version (or commit hash):  0.12.1799
- IDE name and version: Intellij IDEA 2016.2.4
- Java version: 

```
$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```
- OS name and version: 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial
```
- What are you trying to do?
  Debug the `Golang` app step by step
- What would you expect to happen?
  String value in watching variable is same as the output log, and should not be trimmed.
- What happens?
### String variable has been trimmed in Debug mode

Or include a screenshot / video of the issue.

![Snap of Intellj IDEA debug mode](http://shanlin.cn-bj.ufileos.com/snap//snapshot1.png)

**Comment by perolausson** [comment] 2016-10-03 10:41
I am seeing this problem too. It gets confusing. Why is my variable truncated there? 

And then it actually isn't truncated, it's just IDEA telling porkies.

**Comment by scozv** [comment] 2016-10-03 10:45
when I use IDEA to debug Scala or Node, I never saw this issue. so I think this may be a issue for Golang plugin.

**Comment by dlsniper** [comment] 2016-10-03 10:53
@scozv that is because there are different debuggers for different languages. I'll have a look to see how we can improve this. Thank you.

**Comment by dlsniper** [comment] 2016-11-12 19:24
Closing as duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2730 (fixed in https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2489)

**Closed by dlsniper** 2016-11-12 19:24 UTC
Labels: debugger
