### ISSUE TITLE
Debugging works when it wants

### ISSUE THREAD

**Issue by renannprado** [go-lang-plugin-org/go-lang-idea-plugin#2435] opened 2016-04-03 19:38 UTC
- Plugin version (or commit hash): 11.1197
- IDE name and version: 
- Java version: 
![image](https://cloud.githubusercontent.com/assets/2359543/14234479/254344e4-f9ba-11e5-9335-7c2c767ee7c3.png)
- OS name and version: 
![image](https://cloud.githubusercontent.com/assets/2359543/14234499/72fff902-f9ba-11e5-9bb3-d98897973b6c.png)

- What are you trying to do?
Debug go application

- What would you expect to happen?
Breakpoint suspend the execution

- What happens?
Sometimes it suspends, sometimes it doesn't

```go
package main

func main() {
    fmt.Println("Hello, World!")
}
```

**Comment by dlsniper** [comment] 2016-04-03 19:41
This looks like a duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2360 and I'll close it as such. Thanks for reporting.

**Closed by dlsniper** 2016-04-03 19:41 UTC

**Comment by renannprado** [comment] 2016-04-03 19:49
The strange thing is that it was working ok with an earlier version of the plugin (10.1137 I guess) and Intellij IDEA 15.

**Comment by dlsniper** [comment] 2016-04-03 19:51
That may have shipped with a different version of delve. Please provide the logs from the IDE (see the linked issue). Those could help out to see what's the issue there.

**Comment by renannprado** [comment] 2016-04-03 20:07
This is what I get in the logs:

>
 Marker - Apr 3, 2016, 5:05:11 PM
2016-04-03 17:05:26,810 [1548908]   INFO -           #com.goide.dlv.DlvVm - OUT: {"method":"RPCServer.Command","params":[{"Name":"continue"}],"id":1} 
2016-04-03 17:05:36,534 [1558632]   INFO -           #com.goide.dlv.DlvVm - OUT: {"method":"RPCServer.CreateBreakpoint","params":[{"file":"/Users/renannp/development/go/libraries/src/prupru/src/api/services.go","line":28}],"id":2}

**Comment by dlsniper** [comment] 2016-04-03 20:24
Yeah, it looks like a duplicate of that. Thank you
