### ISSUE TITLE
Files under GOPATH are not being resolved

### ISSUE THREAD

**Issue by simonorono** [go-lang-plugin-org/go-lang-idea-plugin#1368] opened 2015-02-24 17:23 UTC
![problem](https://cloud.githubusercontent.com/assets/8929354/6354660/148f5618-bc23-11e4-8760-dc4e9a3b5613.png)

As seen in the image, IntelliJ connot resolve nomis/container/list even though the package DOES exists inside GOPATH.

I'm using IntelliJ Idea 14.0.3 Build #IC 139.1117 running on OpenJDK 1.7.0_75 64 bits, Golang plugin 1.0.alpha#92 and Go 1.4.1

Is there any configuration I'm missing or it is a bug?

**Comment by zolotov** [comment] 2015-02-24 17:37
Please make a screenshot of 'Settings | Languages & Framework | Go Libraries'

**Comment by zolotov** [comment] 2015-02-24 17:37
And screenshot of expanded 'External libraries' node in Project View

**Comment by dlsniper** [comment] 2015-02-24 17:39
@simonorono please create the project in the ```simon``` directory and that should work. Please follow [the tutorial](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project) to create a project when you have a single GOPATH entry and things should work. 

@zolotov this looks like a duplicate of a previous ticket, I'm trying to locate it now.

**Comment by dlsniper** [comment] 2015-02-24 17:42
@simonorono before doing what I've said, please provide @zolotov with the other information, I haven't seen his comments, sorry.

I've found the issue / comment: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1266#issuecomment-73357445

It seems that when ```src```is present in the directory, packages are not considered as being part of the GOPATH.

**Comment by zolotov** [comment] 2015-02-24 17:43
@dlsniper what's the previous ticket? As I see at screenshot GOPATH was found but despite the fact that GOPATH is part of current project it was added as a library.

**Comment by zolotov** [comment] 2015-02-24 17:44
@dlsniper ok, I'll try to figure out what's happening.
@simonorono as a workaround I believe you can open each project separately (not the whole GOPATH)

**Comment by simonorono** [comment] 2015-02-24 17:52
@zolotov Go libraries was empty, I added the GOPATH and GOROOT and the problem was solved.

![window](https://cloud.githubusercontent.com/assets/8929354/6355315/5364dc88-bc27-11e4-8a01-a0aa040777bd.png)

![pro](https://cloud.githubusercontent.com/assets/8929354/6355367/b330cbc2-bc27-11e4-8e84-54af2bdfaede.png)

@dlsniper It even seems to work using the GOPATH as the project, not sure.

![problemno](https://cloud.githubusercontent.com/assets/8929354/6355405/05af3ab4-bc28-11e4-9955-e14a8f925c5a.png)

**Comment by zolotov** [comment] 2015-02-24 17:54
I wonder why the src directory is inside <Go 1.4.1> node. Did you add it in SDK configuration?

**Comment by simonorono** [comment] 2015-02-24 17:57
Both, yes (as seen [here](https://cloud.githubusercontent.com/assets/8929354/6355315/5364dc88-bc27-11e4-8a01-a0aa040777bd.png)). Not adding them used to give me problems in the past.

**Comment by zolotov** [comment] 2015-02-24 18:00
@simonorono I meant another thing. Could you please show attach screenshot of 'File | Project Structure | SDKs | Go 1.4.1'?

**Comment by simonorono** [comment] 2015-02-24 18:06
![sdk](https://cloud.githubusercontent.com/assets/8929354/6355671/dd4375d4-bc29-11e4-8e09-8c51cf046ec1.png)

The only entry I added manually in the Classpath was the src directory of the GOPATH. I used src just because it seemed to be the default behavior.

To add the SDK I used as the SDK home /usr/lib/go; the entry /usr/lib/go/src was added to the classpath automatically.

**Comment by zolotov** [comment] 2015-02-24 18:14
Ok, I've got it now, thanks. I advice you remove '/home/simonorono/Code/Go/src' from SDK because it could lead to strange behaviour :)

I'll add notification for the case when IDEA can't find GOPATH env variable with the suggestion to configure Go Libraries and close the issue after that. Thank you for details.

**Comment by dlsniper** [comment] 2015-02-24 18:17
@zolotov is there any way to make the SDK immutable by the users? Another notification, or even block from the plugin, could be when the users try to add the SDK root to the libraries as well.

**Comment by simonorono** [comment] 2015-02-24 18:18
Thanks to you! Off-topic: Where is the development being made? In the Github project page it says the last commit was made on December 15th, 2014.

**Comment by zolotov** [comment] 2015-02-24 18:19
@simonorono in [1.0.0alpha branch](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/tree/v1.0.0-alpha0)

@dlsniper don't know, will try to figure out.

**Comment by simonorono** [comment] 2015-02-24 18:22
So, what should be added to the global libraries? Just the GOPATH or both the GOPATH and GOROOT?

**Comment by zolotov** [comment] 2015-02-24 18:25
GOROOT is treated as an SDK. And Go Libraries is an internal representation of GOPATH, so GOPATH should be added to the global (or project/module) libraries. Also you can to find out why GOPATH wasn't passed to IDEA in the first place, in this case you have not to configure Go Libraries at all.

**Comment by zolotov** [comment] 2015-02-24 18:33
Usually the reason of such things is a file where environment variable were defined. IDEA tries to take all environment for Xorg or from you default shell in login mode. The problem is that e.g. zsh doesn't read `~/.zshrc` in login mode and bash doesn't read `~/.bashrc` in login mode. So usually as a workaround you can redefine environment variables in the one of the following config files `/etc/<your-shell-configs>`, `~/.profile`, `~/.bash_login`, `~/.zsh_login`, `~/.bash_profile` etc.

**Comment by dlsniper** [comment] 2015-02-24 18:42
@simonorono please read the wiki page, https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project and you'll have all the information you need to setup the project. In case the page above has some things that are not clear, let us know so we can improve on it. Thanks!

**Comment by zolotov** [comment] 2015-02-25 11:28
Notification about empty GOPATH is added

**Closed by zolotov** 2015-02-25 11:28 UTC
