### ISSUE TITLE
1.0.0.alpha#201 Fails to build from Run/Debug Configurations

### ISSUE THREAD

**Issue by niwaywood** [go-lang-plugin-org/go-lang-idea-plugin#1456] opened 2015-03-18 23:13 UTC
I have a project with two files in `package main`. 

![image](https://cloud.githubusercontent.com/assets/3773641/6721278/d2a92d8c-ce1f-11e4-9367-2b07476bcc4e.png)

When I try to build the application using the Run/Debug Configurations it fails because it can't 'see' the handler functions from `handlers.go` (`func main()` is in `wiki.go`).

![image](https://cloud.githubusercontent.com/assets/3773641/6721342/59a7db80-ce20-11e4-9cb5-41ab153d6ee1.png)

There is nothing wrong with the application because it works when I run `go install && gowiki` from the command line.

I am using WebStorm 9.0.3.

**Comment by dlsniper** [comment] 2015-03-18 23:18
Can you also provide what configuration you have for ``` File | Settings | Languages & Frameworks | Go Libraries ``` and where's your go sdk (goroot)? also, if you execute from the command like the same command, ``` /usr/local/go/bin/go build -o output_file_path /Users/nick/.../wiki.go``` what does it happen? Also which Run option have you used to run the command?

**Comment by niwaywood** [comment] 2015-03-18 23:29
Here is my configuration for `Go Libraries`:

![image](https://cloud.githubusercontent.com/assets/3773641/6721499/d22a9128-ce21-11e4-8966-f958f29e8f1e.png)

The first path in the above image is my `GOPATH` and the second is `GOROOT`.

I get the same output when I execute `/usr/local/go/bin/go build -o output_file_path /Users/nick/.../wiki.go` from command line.

I don't know exactly what you mean by "Also which Run option have you used to run the command?", but here is a screenshot of my Run/Debug Configurations

![image](https://cloud.githubusercontent.com/assets/3773641/6721577/c1f742fa-ce22-11e4-85df-037e11ab162e.png)

**Comment by dlsniper** [comment] 2015-03-18 23:34
I see two problems:
- you should remove GOROOT from Go Libraries, that's not needed and it shouldn't be there (there's no such guidance in the readme page afaik, please read the readmes when you try alpha versions ;) )
- if go build outputs the same problem, then the problem is not in the plugin, it's somewhere else.

What do you get if you run ``` go env ```?

**Comment by niwaywood** [comment] 2015-03-18 23:41
Ok

- I just removed GOROOT from Go Libraries as you suggested, I think I put it in there out of desperation once when I was trying to get something to work. Sorry about that.
- I probably should note that the problem only started happening once I refactored the application into 2 files, WebStorm built the application successfully when all of `package main` was in `wiki.go`
- Here is my output from `go env`

```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nick/Documents/code/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by dlsniper** [comment] 2015-03-18 23:52
I'd recommend reading the following links:
- https://golang.org/doc/code.html
- http://blog.golang.org/organizing-go-code

Also I'd highly recommend moving the second file contents to its own package as it makes things easier to maintain and more in line with the Go expectations.

Still, if you want to keep multiple files for the same main package, you need to specify them to the go tool such as ```go run handlers.go wiki.go``` where as ```go run wiki.go``` won't run (just as ```go build wikil.go``` won't work). ```go build``` without any arguments will however properly build the app itself.

@zolotov I'll leave this open and up to you to consider for the runner configuration. The issue is that the go tool expects all the files to be fed to it in this particular case, when there are multiple files in the main package or ```go build``` should be ran directly, without the specific file. I have no data to support the numbers behind it but, at least to the go rules, this doesn't seem to be a popular form of organizing the code.

**Comment by zolotov** [comment] 2015-03-19 00:04
@dlsniper thanks, I'll leave it open for a while as a test case of building

@niwaywood since `go install` works for you could you show me the output of `go install -x` please? Just to known what go build does in your case.

**Comment by niwaywood** [comment] 2015-03-19 00:09
Thanks for the feedback, I have already read the two links you mentioned and I would argue that having multiple files in `package main` goes against Go expectations. The way I see it is that application specific code should refactored into files and non-application specific code should be refactored into libraries. This may come down to personal preference but I just had a look at some open source applications and it seems having multiple `package main` files is quite popular, for example:
- https://github.com/jingweno/nut
- https://github.com/tools/godep

Whether its a popular pattern or not I feel the plugin should still allow it.

@zolotov here is the output of `go install -x`:

`WORK=/var/folders/hf/9hd4pxw10pv4vgp8ts25rhdc0000gn/T/go-build502833202`

**Comment by niwaywood** [comment] 2015-03-19 00:19
@dlsniper you said 

"Still, if you want to keep multiple files for the same main package, you need to specify them to the go tool such as `go run handlers.go wiki.go` where as `go run wiki.go` won't run"

I understand that, but (correct me if I'm wrong) you can't specify extra run parameters like that from the Run/Debug Configurations. Meaning that there is still no way to do this with the plugin/WebStorm. Is this correct or am I missing something?

**Comment by MorganWu** [comment] 2015-03-23 10:20
I have the same problem. It seems the plugin will run under a custom directory, but fail to create the directory. Right now I run in command line under the directory where main file is put, everything is just fine.

**Comment by zolotov** [comment] 2015-03-23 10:54
@MorganWu I didn't understand what `fail to create the directory` means. What directory should be created, why and when? 
You can specify any working directory in run configuration.

**Comment by MorganWu** [comment] 2015-03-23 11:02
Yes, I specified a working directory in my run configuration, like '/gopath/src/xxx.com/dm', but the case is when I printed the first argument (os.Args[0]), I got '/private/var/folders/zb/xtqgq0jd38ddsdq4cjxg3zqc0000gn/T/d1_0go' instead. Am I doing wrong to get the working directory?

**Comment by zolotov** [comment] 2015-03-23 11:23
@MorganWu Args[0] has nothing to do with working directory, it's path to binary file. Use os.Getwd for retrieving working directory.

**Comment by MorganWu** [comment] 2015-03-23 16:27
@zolotov Thanks, actually I got this problem when I was using an open source web framework, which try to retrieve config files in working directory, but uses 'args[0]' in fact. Anyway, I'll do some adjustment accordingly later, thank you.

**Comment by 3dseals** [comment] 2015-04-08 02:21
Hi, i have a problem with idea 14.1 and go plugin 1.0.0.alpha#201 
i can't build or debug the go project
but i can run it with config the goroot and gopath(library)
how could i debugging the go project?any Tutorial for me?
i also try the idea 13 and 0.9x plugin

**Comment by dlsniper** [comment] 2015-04-08 08:16
@3dseals if you are using IDEA 14.1+ please upgrade to the latest version of the plugin, see the README on how to add the alpha channel to the IDE and access it. Also, please open a new issue so that we can address your issue specifically.
As for the whole debugging thing, @zolotov please correct me if I'm wrong, but it's safe to say it's experimental at this point and it's only as good as running gdb manually would be, which is not very good to begin with, for details see this: https://golang.org/doc/gdb.
Thank you.

**Comment by zolotov** [comment] 2015-04-08 10:05
@3dseals debugging doesn't work sorry, we'll look at it in the nearest future. As for running, it works for some cases but not for all, see #1413 and #1414 for details.

Closing issue as a duplicate of #1413 and #1414

**Closed by zolotov** 2015-04-08 10:05 UTC
Labels: feedback required
