### ISSUE TITLE
fmt.Printf '%+v' not detected as a placeholder

### ISSUE THREAD

**Issue by Kaedys** [go-lang-plugin-org/go-lang-idea-plugin#2316] opened 2016-01-29 19:16 UTC
**What version of Go plugin are you using?**
0.9.1069

**What version of IDEA are you using?**
14.1.6

**What version of Java are you using?**
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

**What did you do?**
Used the `%+v` placeholder in a Printf() function.

**What did you expect to see?**
No inspection highlighting.

**What did you see instead?**
![screen shot 2016-01-29 at 1 09 42 pm](https://cloud.githubusercontent.com/assets/9020449/12685443/05be2778-c68a-11e5-8e95-f654707f13bd.png)

All three forms of placeholder in the screenshot are valid, but the `%+v` form (which prints field names of a struct, but not type information like `%#v`) isn't detected as a placeholder, giving an inspection error of `Got 0 placeholder(s) for 1 arguments(s)` (sic, "arguments" has an extra 's')

**Comment by dlsniper** [comment] 2016-01-29 19:18
Hello, thank you for reporting. I'll close this as a duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2194. Thank you for your patience.

**Closed by dlsniper** 2016-01-29 19:18 UTC
Labels: inspections

**Comment by Kaedys** [comment] 2016-01-29 19:44
Oh, my bad, I went back about 2 weeks on issues looking for a similar one.  Didn't realize it'd been reported so far back.

**Comment by dlsniper** [comment] 2016-01-29 19:45
No worries. Thanks for reporting!
