### ISSUE TITLE
Strings cut during debugging

### ISSUE THREAD

**Issue by b5y** [go-lang-plugin-org/go-lang-idea-plugin#2811] opened 2016-10-27 18:41 UTC
- Plugin version (or commit hash): Version: 0.12.1799
- IDE name and version: PyCharm CE 2016.2.3
- Java version: 
  java version "1.8.0_102"
  Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
  Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
- OS name and version: 
  Software:
  
  System Software Overview:
  
    System Version: macOS 10.12 (16A323)
    Kernel Version: Darwin 16.0.0
- What are you trying to do?
  Debugging and/or running program in PyCharm
- What would you expect to happen?
  Correct string output
- What happens?
  String cuts with plugin?

During debugging or running program in PyCharm IDE strings cropped. For instance, last string in `cmd` variable removes at all and `file_` is cuts at the end.

I have tried concatenating string in multiple ways (with bytes.Buffer, + and with 
Sprintf("%s%s%s")). In every time string is not outputs as expected.

``` go
package main

import (
    "fmt"
)

func main() {
    file_ := "/asdsa/asd/gffg/erwy/ytur/qewqe/"
    cmd := fmt.Sprintf("%v%v%v", "adsa -r ", file_, " -I")
    fmt.Println(cmd)
}
```

It is looking as bug. Please confirm or decline my assumption.

**Comment by zolotov** [comment] 2016-10-27 19:15
https://play.golang.org/p/XfkL-ygTTC

<img width="653" alt="screenshot 2016-10-27 22 15 17" src="https://cloud.githubusercontent.com/assets/140920/19781643/dc82ca28-9c92-11e6-9fca-faa3a93b3517.png">

**Comment by zolotov** [comment] 2016-10-27 19:15
Works fine for me

**Comment by b5y** [comment] 2016-10-27 20:20
I have tested it on play golang too. Otherwise I would write this issue on golang's repo, not here :)

OK. I will attach screenshot of this crazy behavior tomorrow. It's really strange.

**Comment by b5y** [comment] 2016-10-28 08:42
![screen shot 2016-10-28 at 11 39 02](https://cloud.githubusercontent.com/assets/1110987/19800232/82994250-9d03-11e6-9705-a6706cc7052a.png)
![screen shot 2016-10-28 at 11 39 12](https://cloud.githubusercontent.com/assets/1110987/19800234/829dbd30-9d03-11e6-8441-0d1fa7f5b4bd.png)
![screen shot 2016-10-28 at 11 39 21](https://cloud.githubusercontent.com/assets/1110987/19800235/82a51206-9d03-11e6-97ab-495122e4657d.png)
![screen shot 2016-10-28 at 11 39 29](https://cloud.githubusercontent.com/assets/1110987/19800233/829b7c14-9d03-11e6-81c7-3725b2929877.png)

**Comment by b5y** [comment] 2016-10-28 08:43
It seems that it is debugger's bug, not plugin. After execution everything works fine.
Pardon moi.

**Comment by b5y** [comment] 2016-10-28 08:49
Btw, it works properly for short strings.

**Comment by dlsniper** [comment] 2016-10-28 09:13
This is actually something we need to fix in the plugin, there's a similar ticket opened on this

**Comment by dlsniper** [comment] 2016-11-12 16:55
Closing as duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2730

**Closed by dlsniper** 2016-11-12 16:55 UTC
Labels: debugger
