### ISSUE TITLE
One line if statements don't parse correctly

### ISSUE THREAD

**Issue by carmandrew** [go-lang-plugin-org/go-lang-idea-plugin#1415] opened 2015-03-05 22:23 UTC
http://play.golang.org/p/uNy-BwWHeq is valid, but the plugin gives these two errors:
![json-to-struct_go_-__s0__-_s0_-____code_s0_](https://cloud.githubusercontent.com/assets/630721/6515889/af909552-c342-11e4-8cab-6e9a8828ba33.png)
![json-to-struct_go_-__s0__-_s0_-____code_s0_](https://cloud.githubusercontent.com/assets/630721/6515904/cf0d2bde-c342-11e4-9ce9-0485a37536ec.png)

On version 1.0.0.alpha#164 of the plugin. Doesn't seem like a super high priority, since `gofmt` will fix this code, but still wanted to point it out. Thanks for all the awesome work recently!

**Comment by dlsniper** [comment] 2015-03-05 22:28
@zolotov could this be a duplicate of : https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1362 . or #1362 have the same cause of this one?

**Comment by zolotov** [comment] 2015-03-05 22:30
@dlsniper I think so

**Closed** 2015-03-15 20:56 UTC
