### ISSUE TITLE
[1.0] Duplicate src on my mac idea

### ISSUE THREAD

**Issue by ElvizLai** [go-lang-plugin-org/go-lang-idea-plugin#1242] opened 2015-02-03 11:57 UTC
![qq20150203-1 2x](https://cloud.githubusercontent.com/assets/501861/6019707/84b55028-abde-11e4-84af-104d81684f81.png)
pic1

![qq20150203-4 2x](https://cloud.githubusercontent.com/assets/501861/6019710/866a0b52-abde-11e4-8a96-bdf0f9ed12dc.png)
pic2

The problem is at the red arrow, I tried to fix the path (pic2) to /Users/ElvizLai/IdeaProjects/Test, but it still have problem like pic1, and when I restart my IDEA, it roll back to pic2.

My IDEA version is 14.0.3, plugin version 1.0.0.alpha#11

**Comment by dlsniper** [comment] 2015-02-03 11:59
@ElvizLai which plugin version do you have? Commit hash would be really helpful if you've built it yourself.

**Comment by ElvizLai** [comment] 2015-02-03 12:01
@dlsniper I downloaded it  from releases, and the version is 1.0.0.alpha#11

**Comment by dlsniper** [comment] 2015-02-03 12:08
I'm not sure this is a duplicate or side effect of #1209

**Comment by ElvizLai** [comment] 2015-02-03 12:41
I tried to built a new project to found out why this happened, when a new project was built, it popup a msg for user to configure the GOPATH like following:

![qq20150203-3 2x](https://cloud.githubusercontent.com/assets/501861/6020229/5b0a8f1c-abe4-11e4-8666-6d5554f8c97c.png)

The path MUST be the root of Project, and WITHOUT src, for example, ..../Text is OK, but ..../Text/src couldn't be work. But even if the config is right, the following looks same like the failure one.
 
![qq20150203-4 2x](https://cloud.githubusercontent.com/assets/501861/6020251/ae98e656-abe4-11e4-9461-5375eb78dcdd.png)

I think this can help you to find out what lead this problem.

**Comment by zolotov** [comment] 2015-02-03 13:32
@ElvizLai thank you for detailed description, it's really useful.

"src" is added intentionally in resolving purposes according to [Workspace doc](https://golang.org/doc/code.html#Workspaces). Indeed it shouldn't be added while compiling, I'll try to figure out why it happens.

**Comment by dlsniper** [comment] 2015-02-03 13:34
@zolotov if it helps, I'm having just ```/home/florin/golang``` not ```/home/florin/golang/src``` in my Global libraries list. Maybe the plugin should reinforce to have paths without ```/src``` added but just their root directory, like in my case?

**Comment by zolotov** [comment] 2015-02-03 13:38
@dlsniper, maybe, I'm not sure about it at the moment, will tell when I'll investigate it.

**Comment by vastbinderj** [comment] 2015-02-15 20:20
As for me, I've add my true GOPATH ```/Users/james/go```, but I was curious if I needed to...

**Comment by dlsniper** [comment] 2015-02-15 20:26
@vastbinderj can you please detail a bit more on that one? What was the problem and how / if you fixed it? It's a bit unclear from your description. Thanks.

**Comment by zolotov** [comment] 2015-03-02 09:40
@vastbinderj, @ElvizLai could you please check it on 1.0.0alpha#164 release? I believe it should be fixed there

**Comment by ElvizLai** [comment] 2015-03-02 11:12
@zolotov I downloaded #164, and modify GOPATH in Languages & Frameworks->Go Libraries->Project libs .
It works well without src, when I added the `src` and run, it shows:

```
src/App.go:4:2: cannot find package "controllers" in any of:
	/usr/local/go/src/controllers (from $GOROOT)
	/Users/ElvizLai/GoWorkSpace/src/controllers (from $GOPATH)
	/Users/ElvizLai/IdeaProjects/YunTu/src/src/controllers
```

The err msg is clear, and user know what's wrong.

**Comment by zolotov** [comment] 2015-03-02 11:38
@ElvizLai ok, thanks for feedback, I'll look at this

**Comment by zolotov** [comment] 2015-03-08 14:46
I still can't reproduce this. But I have couple questions about your configuration.

1. Output contains `/Users/ElvizLai/IdeaProjects/YunTu/src/src/controllers`. And screenshot with Go Libraries configurable don't. So where did you define this path?
2. Did you try to unvoke `go run` in terminal? It's `go run /Users/ElvizLai/IdeaProjects/Test/src/main/main.go` according to screenshots. What's the output for the command?

**Comment by ElvizLai** [comment] 2015-03-09 03:22
@zolotov 
 1、Screenshot and Output looks different because they are not the same project. I configure it in `GOPATH in Languages & Frameworks->Go Libraries->Project libs`.

2、`go run /Users/ElvizLai/IdeaProjects/Test/src/main/main.go` can not be run on terminal, because my Computer's GO PATH is `/Users/ElvizLai/GoWorkSpace`. It's not my IDEA workspace.

**Comment by zolotov** [comment] 2015-03-09 09:20
Could you make all screenshots and output of the same project please? At the moment all screenshots are placed in different comments and have different paths on it.
Or even better, attach sample project that I can use to recreate the issue.

**Comment by zolotov** [comment] 2015-03-28 14:04
Any news on this?

**Comment by dlsniper** [comment] 2015-05-01 19:42
I'll close this due to lack of feedback. Please reopen if there's anything new.

**Closed by dlsniper** 2015-05-01 19:42 UTC
Labels: feedback required
