### ISSUE TITLE
Show not enough wrong return value

### ISSUE THREAD

**Issue by kostonstyle** [go-lang-plugin-org/go-lang-idea-plugin#1352] opened 2015-02-22 13:49 UTC
Hi dev team

I am using github.com/garyburd/redigo/redis to connect with redis server. When I call the statement
```go
Do(commandName string, args ...interface{}) (reply interface{}, err error)
```
as you can see, it return 2 parameters reply and err. When I want to fetch data from redis I use the statement
```go
 v, err := redis.Values(conn.Do("HGETALL", id))
```
The plugin shows error, that is not enough arguments is passed to Values function

![image](https://cloud.githubusercontent.com/assets/701611/6318711/c7b65c7e-baa1-11e4-8b4a-eef7d8ecdaa9.png)
but  redis.Do function returns two values.

**Comment by dlsniper** [comment] 2015-02-22 13:59
Hi @kostonstyle,

Can you give us some details about the plugin version and IDE version you are using?
Thanks.

**Comment by kostonstyle** [comment] 2015-02-22 16:17
Of course
![image](https://cloud.githubusercontent.com/assets/701611/6319279/aca10960-bab6-11e4-8cb5-28a1fc8fd420.png)
Thanks

**Comment by dlsniper** [comment] 2015-02-22 20:01
I've managed to replicate this and it looks like a duplicate of #1343 or #1222. Please watch those for when this is fixed. Thank you.

**Closed by dlsniper** 2015-02-22 20:01 UTC
Labels: feedback required
