### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by zolotov** [go-lang-plugin-org/go-lang-idea-plugin#2331] opened 2016-02-08 09:36 UTC
```go
package main

import (
	"net/http"
	"encoding/json"
	"fmt"
)

type(
	InputParams interface {
		Validate() (bool, error)
	}
)
​
func Encode(r *http.Request, object *InputParams) error {
	dec := json.NewDecoder(r.Body)
	defer r.Body.Close()
	​
	if err := dec.Decode(object); err != nil {
		// Log
		return err
	}
	​
	valid, err := object.Validate() // unresolved
	if err != nil {
		return err
	}
	if valid != true {
		return fmt.Errorf("Package not valid")
	}
	​
	return nil
}
```

**Comment by EagleMoor** [comment] 2016-02-08 09:46
![screen shot 2016-02-08 at 11 57 49](https://cloud.githubusercontent.com/assets/1461295/12882321/e5861e7c-ce61-11e5-8b5b-a73aa158d2d9.png)

**Comment by dlsniper** [comment] 2016-02-08 09:56
The not resolving part is correct actually, https://play.golang.org/p/GAB8EsSCqC
The method is defined on the interface, not on the interface pointer, see the error:
```
prog.go:24: object.Validate undefined (type *InputParams is pointer to interface, not interface)
```
Maybe we should provide a better error message not define it as unresolved?

**Comment by ignatov** [comment] 2016-03-07 13:28
Works as intended. An additional inspection could be added. @dlsniper Please create a separate issue, thanks.

**Closed by ignatov** 2016-03-07 13:28 UTC
Labels: resolving

**Comment by dlsniper** [comment] 2016-03-07 18:47
@ignatov we have an issue for it, https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2204, I've updated it to include the above sample as well.
