### ISSUE TITLE
Inconsistent syntax coloring in show diff window

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1353] opened 2015-02-22 14:04 UTC
Left pane has generic syntax coloring or something. See screenshot:
![screenshot - 220215 - 16 00 38](https://cloud.githubusercontent.com/assets/4119321/6318780/32e71e34-baac-11e4-8f50-3c1aba02220a.png)

Idea: IU-140.2493.5
Plugin: 0.9.92

**Comment by dlsniper** [comment] 2015-02-22 14:13
@zolotov and @ignatov I'm not sure this one is caused by the go plugin, the git plugin or by the IDE.
I've tried with the same version as @dmitry-vovk and I only have the keywords highlighted in my diffs. 

This happens even with 44ad224d3bd7cb87b13fed97b5b9cd434cbc45e9 so it's something that definitely is not affected by the highlight support as we've just merged that and 1.0.0-alpha#92 was released before it, last week.

**Comment by ignatov** [comment] 2015-04-25 15:24
The left editor has only highlighting from the lexer. Sure it's a not an issue for the Go plugin.

**Closed by ignatov** 2015-04-25 15:24 UTC
Labels: uncertain am I

**Comment by dlsniper** [comment] 2015-04-28 21:54
I've noticed that in the latest IDEA version, 141.814.3 (EAP for 14.1.3) this works between files that are on disk but it doesn't work between git revisions for the same file. And I think that's ok as the IDE couldn't be able to properly analyze the file properly from a previous revisions as other things might change as well which would render the analysis useless.

**Comment by ignatov** [comment] 2015-04-29 09:56
Please see the platform issue: https://youtrack.jetbrains.com/issue/IDEA-115600
