### ISSUE TITLE
Cant seem to get debugging working

### ISSUE THREAD

**Issue by jondunning** [go-lang-plugin-org/go-lang-idea-plugin#1406] opened 2015-03-02 21:58 UTC
Hi, 

I followed various instructions online but to no avail. The debug button doesn't seem to trigger anything?

Im running IntelliJ 14 CE with the newest build of go-lang-idea-plugin.

Any advice would be grateful.

Thanks,

Jon

**Comment by dlsniper** [comment] 2015-03-02 22:11
At the moment that part of the plugin is not working as intended and there are not many efforts done to make it work. The reason is that gdb doesn't work well with cgo and gccgo support is untested (by me at least), aside from the fact that gccgo is usually behind the cgo version by 1-2 releases at least.

You can follow: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1252 for when Delve will be integrated into the plugin but at the moment I've had some availability issues which forced me to stop working on IDE support for Delve.

**Comment by dlsniper** [comment] 2015-03-02 22:13
I'll leave this open to @zolotov in case there's something I'm missing.

**Comment by dlsniper** [comment] 2015-05-01 08:37
Closing this for now.

**Closed by dlsniper** 2015-05-01 08:37 UTC
