### ISSUE TITLE
could not launch process: could not get thread count

### ISSUE THREAD

**Issue by cdoco** [go-lang-plugin-org/go-lang-idea-plugin#2847] opened 2016-12-10 15:06 UTC
- Plugin version (or commit hash): 0.12.1799
- IDE name and version: PhpStorm 2016.2.2
- Java version: 
- OS name and version: MacOS 10.12.1

Debug Mode

```go
"/Users/Cdoco/Library/Application Support/PhpStorm2016.2/Go/lib/dlv/mac/dlv" --listen=localhost:61816 --headless=true exec /private/var/folders/69/x7fwhs3x4dx5wmq6vtjrpz040000gn/T/zyapigo --
GOROOT=/usr/local/Cellar/go/1.7.4/libexec
GOPATH=/data/gosrc
/usr/local/Cellar/go/1.7.4/libexec/bin/go build -o /private/var/folders/69/x7fwhs3x4dx5wmq6vtjrpz040000gn/T/zyapigo -gcflags "-N -l" /data/gosrc/src/zyapi/main.go
could not launch process: could not get thread count

Process finished with exit code 1
```

**Comment by dlsniper** [comment] 2016-12-10 15:07
Hi,

Unfortunately this is a problem caused by the compiler that the plugin is using.
I'll close this as a duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2810, you can watch that for more updates when we'll have them.

**Closed by dlsniper** 2016-12-10 15:07 UTC
