### ISSUE TITLE
Import autocomplete uses Godeps vendor directory

### ISSUE THREAD

**Issue by arekkas** [go-lang-plugin-org/go-lang-idea-plugin#2685] opened 2016-07-20 08:17 UTC
- Plugin version (or commit hash): v0.12.1625
- IDE name and version: IntelliJ 2016.2

- Java version: 
```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

- OS name and version: Windows 10 64 Bit 

- What are you trying to do?

I am using autocomplete for import statements

- What would you expect to happen?

That import statements like `import "github.com/Sirupsen/logrus"` are being added automatically when writing `logrus.Println`

- What happens?

`"github.com/openshift/origin/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus"` is being imported instead. This happens with other libraries that reside in Godeps / vendor directory as well.

**Comment by zolotov** [comment] 2016-07-20 09:45
cannot recreate. If I have `github.com/Sirupsen/logrus` and `github.com/openshift/origin` then plugin doesn't import anything automatically and suggests to select import by hand. Any additional details to recreate?

**Comment by dlsniper** [comment] 2016-07-20 09:46
might be related to: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1900

**Comment by arekkas** [comment] 2016-07-20 09:49
@zolotov I think I messed up - it wasn't the IDE's autocomplete but me using the wrong prediction as described in #1900

@dlsniper yes I think it is

![asdfasdfasdfasdfasdf](https://cloud.githubusercontent.com/assets/3372410/16982435/07b48ab8-4e70-11e6-95b9-3be3bf18a8c4.PNG)

**Comment by zolotov** [comment] 2016-07-20 09:50
@dlsniper nice catch!

@arekkas I see, thanks for update.

Closing as duplicate of #1900

**Closed by zolotov** 2016-07-20 09:50 UTC
Labels: feedback required
