### ISSUE TITLE
Support inline template annotations in HTML pages

### ISSUE THREAD

**Issue by bingamic** [go-lang-plugin-org/go-lang-idea-plugin#2326] opened 2016-02-04 11:38 UTC
What version of Go plugin are you using?

0.10.1111

•What version of IDEA are you using?

IntelliJ 15.03 Ultimate (win10)

•What version of Java are you using?

Oracle JDK 8 - 1.8.0_66

Currently errors show:

![0](https://cloud.githubusercontent.com/assets/17033211/12813997/54f75940-cb44-11e5-9565-af220d28a1f7.png)

**Comment by dlsniper** [comment] 2016-02-04 11:41
Hi. Go templates are not supported yet, that's why you are receiving the errors. Please follow https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/351 to get an update once this feature goes live. I'll close this for now as a duplicate of that issue.

**Closed by dlsniper** 2016-02-04 11:41 UTC

**Comment by bingamic** [comment] 2016-02-04 11:43
No problem.. Thanks!
