### ISSUE TITLE
Breakpoints for debuging couldn't work well.

### ISSUE THREAD

**Issue by hiromaily** [go-lang-plugin-org/go-lang-idea-plugin#1969] opened 2015-11-06 00:50 UTC
As title, I think debug function don't work well on IntelliJ IDEA 15.
I'm not sure, this issue is only IDEA 15 or IDEA 14 or below as well.

Though setting breakpoints on the left of certain lines I want to check variables, running can't stop.

My developping environment is below.
* IntelliJ IDEA 15 Community Edition
* Go plugin version 0.10.607
* MAC OS 10.11.1

**Comment by glycerine** [comment] 2015-11-06 02:03
are you using gdb or delve? 

This is typical and expected under gdb. You should be using delve. Please confirm you have delve installed and that delve runs fine from the command line.

**Comment by hiromaily** [comment] 2015-11-06 02:11
I thought debuging function was included on plugin, that's why I didn't care which I use gdb or delve.
Do you mean, besides installing IntelliJ IDEA and go-lang-idea plugin, I have to install delve and run??

**Comment by dlsniper** [comment] 2015-11-06 07:14
Hi, the plugin is using delve, I can confirm that, no need to investigate. 
What's the name of your ru configuration? There was a bug in deleve which prevented it to debug executables with a space in their name and when debugging the name of the run configuration is used as executable name. Can you please post a screenshot of your run configuration? Thank you.

**Comment by hiromaily** [comment] 2015-11-06 08:29
Thanks!
Name of run configuration is "testmain" or "test" because of checking function right now.

<img width="1075" alt="screenshot" src="https://cloud.githubusercontent.com/assets/301692/10992711/e6f6f4b6-84ab-11e5-9dfb-1eb15d5ac8ea.png">

**Comment by dlsniper** [comment] 2015-11-06 18:52
Hi, did it worked?

**Comment by hiromaily** [comment] 2015-11-07 00:19
It doesn't work.

**Comment by dlsniper** [comment] 2015-11-07 00:24
Can you share some code sample that can reproduce this?

**Comment by hiromaily** [comment] 2015-11-07 00:37
I found another facts.

I think code don't matter to working for dubug.
Because It can work I tried that on another macbook using IDEA 14.
That machine did install nothing specials.

**Comment by hiromaily** [comment] 2015-11-07 00:39
I guess  this issue is only on IDEA 15.

**Comment by dlsniper** [comment] 2015-11-07 00:56
I really don't know how to help you out unfortunately. The problem is too generic and there's not enough information to replicate the issue / understand it. 

Can you post a screenshot of Settings -> Languages & Frameworks -> Go -> Go libraries. 
Also where is your Go project located at? And can you please post a screenshot of the console tab when you run the debugger? 

Thank you.

**Comment by hiromaily** [comment] 2015-11-07 00:58
I'm sorry, it's finally worked well after canged directory layer of source files.
I try check more deeply and I report that.
Thanks so much for your great help!!

**Comment by dlsniper** [comment] 2015-11-07 01:01
Happy to help.
It would be interesting to know what you changed and from what so that this can be prevented in the future.
Let me know if I should close this. Thank you.

**Comment by hiromaily** [comment] 2015-11-07 02:47
Hi, guys.
I may find the cause of this issue.

In conclusion, project directory made by symbolic link can't be debugged. 
I reproduce that as below.

First create go directory including go file somewhere.
And then set symbolic link of that to within GOPATH direcotry.
<img width="426" alt="symbolic" src="https://cloud.githubusercontent.com/assets/301692/11013142/a921dfa4-8544-11e5-95e9-13f967be7370.png">

/User/hy/abcd.com is directory including go file created for test.
GOPAHT is /User/hy/work/go

And then set Run/Debug configuration. File path is symbolic link.
<img width="1072" alt="config" src="https://cloud.githubusercontent.com/assets/301692/11013158/0888b774-8545-11e5-83e9-8b5fac56c98a.png">

Under that environment, debugging couldn't work in my case.

**Comment by hiromaily** [comment] 2015-11-07 03:45
Ideally, I want to use symbolic link in project directory.

**Comment by dlsniper** [comment] 2015-11-07 11:32
Closing as a duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1880

**Closed by dlsniper** 2015-11-07 11:32 UTC
Labels: feedback required
