### ISSUE TITLE
The GOPATH variable can not be changed.

### ISSUE THREAD

**Issue by rburton** [go-lang-plugin-org/go-lang-idea-plugin#1973] opened 2015-11-07 00:49 UTC
I had an old project to play with Go within Intellij, but now that I started a new project, the GOPATH can not be changed. When I go to Modules and change the export for GOPATH to something new, it always ends up using the original value set.

I tried invalidating the cache, uninstalling the plug-in, removing the GOPATH and resetting it again, etc. and it keeps showing the old path.

Using Go 1.5.1 and Intellij 15

**Comment by dlsniper** [comment] 2015-11-07 00:53
Please specify which plugin version you have as that should help in narrowing the issue.
Also, please go to Settings -> Languages & Frameworks -> Go -> Go Libraries and see what values you have there. If you are not sure what to do next, please attach a screenshot and explain what you'd like to have as the new Go path.
Once I have the screenshot I'll be able to explain a bit more (but I first need to understand what's the current setup like).

Thank you.

**Comment by dlsniper** [comment] 2015-11-07 01:04
I've understood from your tweet that you've managed to fix this by removing the `.idea` folder. Can you please share how you reproduced the issue? Thank you.

**Comment by rburton** [comment] 2015-11-07 01:10
Plug-in version is 0.10.607

For the "Go Libraries" I have "Project Libraries" set to include my current working directory. Sadly, this is after I remove the .idea directory. I should have kept what was there before. I do remember those, the Global Libraries had the prior project. 

I was making changes in the Module settings and I think that was overridden by the settings here. I did that because that's how I was initially promoted to set the values before.

Let me do this. Tomorrow, I'll try to create the steps to reproduce the problem. e.g., removing the plug-in, using the other project, setting the GOPATH like I did before, etc.

Once I can reproduce it, I'll share the steps.

**Comment by dlsniper** [comment] 2015-11-07 01:18
Ok, so I think it was because you played around with all those things :) 

All you need to do is to set Settings -> Languages & Frameworks -> Go -> Go Libraries -> Global Libraries to what value you have in your environment for GOPATH and it should be good to go. This applies if you have the one GOPATH value for everything. 

If you have a GOPATH per project, then you need configure the Project Libraries entry instead as that entry is per project (your paths have to respect the GOPATH conventions with the root directory containing the `bin`, `pkg` and `src` directories).

As far as I remember, when the plugin is installed it opens a message containing a link to help you setup your first project with the plugin, which points to this: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project Please read messages from the plugin(s), at least the Go plugin displays the minimum and needed messages only.

Thank you.

**Comment by dlsniper** [comment] 2015-11-17 11:24
I'll close this as there's no feedback for a while. @rburton please feel free to reopen this if there's any updates. Thank you.

**Closed by dlsniper** 2015-11-17 11:24 UTC
Labels: feedback required
