### ISSUE TITLE
Freshly built plugin cannot be installed in 140.2110.5

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1255] opened 2015-02-04 15:04 UTC
I compiled the current master against IU-140.2110.5 according to instructions from howtobuild.md, got file google-go-language.jar in compile dir:
```
package:
      [jar] Building jar: /home/wolf/Projects/go-lang-idea-plugin/google-go-language.jar
```
But attempt to install it using "Install plugin from disk..." shows error "Plugin 'Go language (golang.org) support plugin' is incompatible with this installation"

**Comment by dlsniper** [comment] 2015-02-04 15:05
I'll close this one as it's a duplicate of #1245. Please follow it there.
Currently the plugin won't compile against IDEA 14.1

**Closed by dlsniper** 2015-02-04 15:05 UTC

**Comment by dlsniper** [comment] 2015-02-04 15:13
Also, in the docs it says the IDEA version starts with 139 ;)
