### ISSUE TITLE
debug could not work when project under symbolink

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [go-lang-plugin-org/go-lang-idea-plugin#1971] opened 2015-11-06 15:00 UTC
hello, when creating project under symbolink, debug point could not work 

here is my golang path
```
export GOROOT=~/golang/go
export GOPATH=~/golang/3rdLibs:~/golang/myLibs:~/golang/myApps
export GOBIN=
export PATH=$GOROOT/bin:${GOPATH//://bin:}/bin:$PATH
```

please pay attention to dir "~/golang/myApps"

i create golang project symbolink for dir "~/golang/myApps/src"(of course subdir "src" was existed)
```
xxx@xxx-debian:~/Projects$ ln -s ~/golang/myApps/src ./golang
xxx@xxx-debian:~/Projects$ pwd
/home/xxx/Projects
xxx@xxx-debian:~/Projects$ 
```

these are the background above.

i create golang project by webstorm11, plugin version 0.10.612(debian, linux64)
when i use project path
```
~/golang/myApps/src/MyApp
```
everything works fine, but when i use path
```
~/Projects/golang/MyApp
```
debug point could not hit, but the two paths are the same physical path

as the two path are the same physical paths, i removed this project and reimport it with different "path name", results are the same,
```
when path is real physical path "~/golang/myApps/src/MyApp", debug point  works fine
when path is symbolink path "~/Projects/golang/MyApp", debug point could not break
```

test MyApp.go is quite simple
```
package main

import "fmt"

func main() {
	fmt.Println("asdasdasd")
}
```

my env
```
debian8.2 amd64
webstorm11
plugin version 0.10.612
```
the plugin version seems to be strange, is that right? i add url "https://plugins.jetbrains.com/plugins/nightly/5047" to rep, and install it this morning today.

**Comment by ignatov** [comment] 2015-11-06 17:01
A possible duplicate of #1880?

**Comment by ignatov** [comment] 2015-11-07 11:55
Closed as a duplicate.

**Closed by ignatov** 2015-11-07 11:55 UTC
Labels: debugger
