### ISSUE TITLE
go-lang-idea-plugin--485 debug application error

### ISSUE THREAD

**Issue by Hyzhou** [go-lang-plugin-org/go-lang-idea-plugin#1889] opened 2015-09-24 09:18 UTC
Error running helloworld.go: 
Cannot run program "/Users/hyzhou/Library/Application Support/IntelliJIdea14/intellij-go.jar/lib/dlv/mac/dlv" (in directory "/Users/hyzhou/Document/Code/Scattered/Go/src"): error=20, Not a directory

**Comment by dlsniper** [comment] 2015-09-24 09:29
Hi @Hyzhou, can you please share your run configuration?
Also any logs from the IDE would be helpful. Thank

**Comment by zolotov** [comment] 2015-09-24 09:43
And attach screenshot of run configuration please

**Comment by Hyzhou** [comment] 2015-09-25 02:16
![2015-09-25 10 10 25 2](https://cloud.githubusercontent.com/assets/5910417/10091429/d85d69d0-636d-11e5-91ae-6674d1f0f692.png)
![2015-09-25 10 10 53 2](https://cloud.githubusercontent.com/assets/5910417/10091430/d8963044-636d-11e5-8d62-238fa35e0e6b.png)

@zolotov @dlsniper  Sorry, I can not find my log in Ideal, The build and run is ok, But debug is not.

**Comment by dlsniper** [comment] 2015-09-25 08:47
Hi @Hyzhou thanks for the details.
It looks like a duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1873 for which we have the issue: https://github.com/derekparker/delve/issues/239 .
As a workaround until it's fixed on delves side, please rename the run configuration from `Build ... and run` to something like `helloworld`. This should fix it.
I'll close this for now but please feel free to reopen it / comment if it's not fixed.
Thank you.

**Closed by dlsniper** 2015-09-25 08:47 UTC
Labels: feedback required
