### ISSUE TITLE
Debug: Add ability to attach to a local running  process

### ISSUE THREAD

**Issue by Scratch-net** [go-lang-plugin-org/go-lang-idea-plugin#2710] opened 2016-08-05 06:58 UTC
- Plugin version (or commit hash):  v0.12.1724
- IDE name and version: Idea 2016.2.1
- Java version:
- OS name and version: Windows 10 x64

- What are you trying to do? Attach to a running process

- What would you expect to happen? Be able to attach to a local running  process

- What happens? The functionality is absent 

As Delve supports attaching, it would be nice to be able to use it in IDE. Is it possible? Would save much time when debugging running microservices

**Comment by dlsniper** [comment] 2016-08-05 07:24
I agree. However I'll close this as a duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/620 please keep an eye on that, we need thanks.

**Closed by dlsniper** 2016-08-05 07:24 UTC

**Comment by Scratch-net** [comment] 2016-08-05 07:25
Yep, sorry for the duplicate

**Comment by dlsniper** [comment] 2016-08-05 07:36
Oh my! I'm soo sorry, I didn't meant to write that we need thanks, I wanted to say that we'll update that, thanks. Sooo sorry. (i have the excuse it's morning for me)

**Comment by Scratch-net** [comment] 2016-08-05 07:45
no problem ) Thanks for your great work
