### ISSUE TITLE
After saved run gofmt

### ISSUE THREAD

**Issue by kostonstyle** [go-lang-plugin-org/go-lang-idea-plugin#1361] opened 2015-02-23 15:38 UTC
Hi
Is it possible to customize, that gofmt should execute after saving file?

Thanks

**Comment by dlsniper** [comment] 2015-02-23 15:45
Closing this as a duplicate of #1324

**Closed by dlsniper** 2015-02-23 15:45 UTC

**Comment by kostonstyle** [comment] 2015-02-23 20:39
Sorry thanks.
