### ISSUE TITLE
gotest project can not debug

### ISSUE THREAD

**Issue by ismlsmile** [go-lang-plugin-org/go-lang-idea-plugin#2764] opened 2016-09-02 09:18 UTC
- Plugin version (or commit hash):
0.12.1799
- IDE name and version:
2016.2.3
- Java version:
java 8
- OS name and version: 
Windows 7
- What are you trying to do?
debug go test project
- What would you expect to happen?

- What happens?
debug button is disabled

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.
![1](https://cloud.githubusercontent.com/assets/1876179/18199014/2a03b466-7131-11e6-93f8-dc1cae35ae11.png)
![2](https://cloud.githubusercontent.com/assets/1876179/18199018/2e221e7a-7131-11e6-80be-76720c687048.png)

**Comment by dlsniper** [comment] 2016-09-02 09:21
Closing as duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1855

**Closed by dlsniper** 2016-09-02 09:21 UTC
