### ISSUE TITLE
Compile simple go project using GAE sdk

### ISSUE THREAD

**Issue by juanibiapina** [go-lang-plugin-org/go-lang-idea-plugin#1402] opened 2015-03-02 11:29 UTC
Intellij 14.0.3
OSX Yosemite
JDK 1.8

Setup:
  - Do not set GOPATH or GOROOT
  - Create a new project and add a `main.go` file that prints "hello world".

What works:
  - Set up a go sdk using go from homebrew (usually in /usr/local/Cellar/go/1.4/libexec)
  - Compile and try to run `main.go`

What doesn't work:
  - Set up a go sdk using `go1.2.1 (appengine-1.9.17)`
  - Run `main.go`

Error: cannot find GOROOT directory: /private/var/folders/zj/06c51mbs71z4r22r59jzffjm003chb/T/appengine/go_appengine/goroot

I don't know if it should be possible to use it like this. I'm just trying to recreate the problems I have with appengine in the simplest possible go project.

**Comment by dlsniper** [comment] 2015-03-02 12:52
Closing this as a duplicate of #1387

**Closed by dlsniper** 2015-03-02 12:52 UTC
Labels: GAE support

**Comment by juanibiapina** [comment] 2015-03-02 13:51
I don't see anything related to this bug on #1387. Or do you mean you plan to resolve this bug and others when you rewrite appengine support?

**Comment by dlsniper** [comment] 2015-03-02 14:47
The bug you reported is that there's no way to run the AppEngine app, which is exactly what is described in the mentioned ticket. Just because it errors faster / in a different point, it doesn't mean it will work if this is fixed.

As you can see from the previous discussions, as well as milestone target, this might make it or not in the initial release as this is not considered a priority or a critical feature. The dev server can be manually ran just as it would be without the IDE.

If you'd like to see this done faster, you can always contribute to the plugin, which we, and the rest of the community, would very much appreciate.

Thank you.

**Comment by juanibiapina** [comment] 2015-03-02 15:06
This is not an appengine app, and I'm not trying to run the server, only trying to use the appengine sdk to compile a hello world go project. I believe this should be fixed as a first step to get appengine working, since it is probably something simple.

I have already started working on the plugin development, but given my inexperience, I don't yet how to debug failures.

**Comment by dlsniper** [comment] 2015-03-02 15:54
Here's what happens when I'm trying to run a go app with the Go AppEngine SDK:

```bash
$ /usr/local/go_appengine/goroot/bin/goapp run ~/golang/src/u/u.go    
go: cannot find GOROOT directory: /tmp/appengine/go_appengine/goroot

$ GOPATH=/usr/local/go_appengine/goroot /usr/local/go_appengine/goroot/bin/goapp run ~/golang/src/u/u.go 
go: cannot find GOROOT directory: /tmp/appengine/go_appengine/goroot
```

**Comment by dlsniper** [comment] 2015-03-02 15:56
Unless either @zolotov or @ignatov override me on this one, I'd say running normal Go apps with an AppEngine is really not a priority as there's the straight forward method of just running Go apps with the Go SDK.

**Comment by juanibiapina** [comment] 2015-03-02 16:01
Awesome. So that's an appengine problem. I failed to notice this.
