### ISSUE TITLE
Resolve local import the same as godep

### ISSUE THREAD

**Issue by drichelson** [go-lang-plugin-org/go-lang-idea-plugin#2328] opened 2016-02-04 20:14 UTC
I'll try to explain this based on this example project: https://github.com/drichelson/golang-idea-relative-imports

I use godep with various projects that live under my $GOPATH
I can use the plugin just fine for some of these projects by setting my project library settings to this:
![screen shot 2016-02-04 at 12 09 18 pm](https://cloud.githubusercontent.com/assets/602409/12828196/339d9540-cb38-11e5-8e5a-8c8b99c2153a.png)

This works fine as long as I'm only defining one package per project, but breaks down as in my example repo when importing "github.com/drichelson/golang-idea-relative-imports/localPackage1" which godep somehow figures out is in my project's source and builds just fine. 

The plugin will only accept this import if it is in the form of a relative path:  "./localPackage1", but this breaks godep: 

```
>godep go build
can't load package: /Users/dan/workspace/go/src/github.com/drichelson/golang-idea-relative-imports/main.go:4:2: local import "./localPackage1" in non-local package
godep: go exit status 1
```

What is involved to make the plugin resolve the import "github.com/drichelson/golang-idea-relative-imports/localPackage1"; the same way it currently resolves "./localPackage1" ? 

I've looked at the source code and would like to help, but if someone could point me in the right direction that would be great.

**Comment by dlsniper** [comment] 2016-02-04 20:27
This works correctly with godep as the tool itself will prepend the ` <project-dir>/Godeps/_workspace ` to GOPATH such as ` GOPATH=<project-dir>/Godeps/_workspace:GOPATH ` and then the go tool will search the package first in the `_workspace` dir then the rest of the GOPATH entries.

The order go tool resolves packages is (for a GOPATH composed of multiple packages):
```
$GOROOT (Go SDK)
/first/GOPATH/entry/
/second/GOPATH/entry/
...
/other/GOPATH/entry/
```

Imho this is a duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1790 + the usage of a vendoring tool (which would be: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1820)

**Comment by dlsniper** [comment] 2016-02-04 20:30
I wonder if the ` Auto-import -> Exclude from Import and Completion ` could be made to accept full system paths as well as that would then provide at least a temporary solution for this.

**Comment by zolotov** [comment] 2016-02-05 07:59
> Imho this is a duplicate of #1790 + the usage of a vendoring tool (which would be: #1820)

yes

> I wonder if the Auto-import -> Exclude from Import and Completion could be made to accept full system paths as well as that would then provide at least a temporary solution for this.

no, first of all, it won't fix anything. In the second it's project setting, so it's shareable and shouldn't depend on paths. In the third, using FS paths instead of language-specific abstractions – it's a step back on understanding language by IDE.

**Closed by zolotov** 2016-02-05 07:59 UTC
