### ISSUE TITLE
AssertionError in PSI parsing

### ISSUE THREAD

**Issue by ansel1** [go-lang-plugin-org/go-lang-idea-plugin#1508] opened 2015-03-31 15:18 UTC
Getting a lot of these with the pen package:

```
10:26:26 AM AssertionError
            Stub and PSI element type mismatch in pem.go: stub GoFunctionDeclarationStub, AST VAR_SPEC; Element(VAR_SPEC)
            file=GO_FILE, modStamp=0
            stub debugInfo=created in getStubTree(); with backReference
            document before=DocumentImpl[file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go]
            latestIndexedStub=null
            viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go, content=DocumentContent{size=6858}}
            viewProvider stamp: 0; file stamp: 0; file modCount: 1424234314000; file length: 6858
            doc saved: true; doc stamp: 0; doc size: 6858; committed: true
            indexing info: no data
            ------------
```

RubyMine 7.1 EAP 141.373 on OSX 10.10.3, go 1.4.2, latest plugin from alpha plugin repo as of today's date (sry, seems like the plugin reports the wrong plugin version in the IDE's plugin settings)

**Comment by dlsniper** [comment] 2015-03-31 15:25
I'm sorry, I can't replicate this with IDEA Ultimate

**Comment by zolotov** [comment] 2015-03-31 15:37
Invoke File | invalidate Caches

> seems like the plugin reports the wrong plugin version in the IDE's plugin settings

What does it mean?

**Comment by ansel1** [comment] 2015-03-31 17:21
I've tried invalidating caches.

The plugin settings comment is about the version number shown in the plugin dialog.  I think the plugin version is 1.0.0.something at this point, but the plugin manager still shows it as 0.9.x.  I'll attach a screenshot.

Firing up IDEA 14.1 to see if these issues are related to the ruby mine eap...the version in the plugin manager is still 0.9.x...will update about whether the PSI assertions go away.

![golang plugin screenshot](https://cloud.githubusercontent.com/assets/107825/6924757/baebefbc-d7a8-11e4-9011-daf9c3fb43b6.png)

**Comment by dlsniper** [comment] 2015-03-31 17:23
@ansel1 can you uninstall the previous version of the plugin first then see if you can install the plugin from the repository? Thanks.

**Comment by dlsniper** [comment] 2015-03-31 17:24
P.S. the screenshot you've show shows the plugin version from the plugin repository not the one you have installed, which is the one @zolotov was asking about.

**Comment by zolotov** [comment] 2015-03-31 17:26
0.9.xxx is ok. 1.0.0.xxx is greater than 1.0.0, right? We won't publish 1.0.0.xxx before 1.0.0.

**Comment by ansel1** [comment] 2015-03-31 17:31
Ah, I see.  You do your version nums a little different than us, it threw me.  0.9.223 is current alpha release then.

**Comment by dlsniper** [comment] 2015-03-31 17:35
As a small mention, if you chose to build the plugin from sources (because nightly isn't fast enough), the version number there is 1.0 so it will prevent the auto-update to work until we release 1.0 stable so please be careful about that. Also, when reporting issues, in this case, please also send the git commit hash in the issue. Thanks.

**Comment by zolotov** [comment] 2015-03-31 17:37
> 0.9.223 is current alpha release then.

Yep.

About the issue. Usually this exception means that some committer forgot to update index version, it's not fatal, Invalidate Caches just works and you'll never get the exception again (at least till the next update). But perhaps it's indexing bug, in this case you'll see the exception again and again. So. I'm going to close the issue now, but if you'll get the exception again please ping me and I'll reopen the issue and will investigate the problem. Thanks.

**Comment by ansel1** [comment] 2015-03-31 17:39
When in the rubymine 7.1 eap, the error happens repeatedly.  If you are editing a file which imports encoding/pem.  Eventually, it seems like indexing gives up, and stuff like syntax highlighting and completion is sort of only half enabled.

But I'm seeing it at all on idea 14.1.

**Comment by zolotov** [comment] 2015-03-31 17:41
Ok, will check it.

**Comment by ansel1** [comment] 2015-03-31 17:42
Importing crypto/x509 may also be triggering it

**Comment by ansel1** [comment] 2015-04-01 20:15
I'm getting errors now on idea 14.1.1 (OS X 10.10.3, plugin 0.9.223) parsing file which imports encoding/pem.  Manifests as some syntax highlighting flashing on and off, and the idea logs filling up with this:

```
java.lang.AssertionError: Stub and PSI element type mismatch in pem.go: stub GoFunctionDeclarationStub, AST VAR_SPEC; Element(VAR_SPEC)
 file=GO_FILE, modStamp=0
 stub debugInfo=created in getStubTree(); with backReference
 document before=DocumentImpl[file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go]
latestIndexedStub=com.intellij.psi.stubs.StubTree@3c21de73
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go, content=DocumentContent{size=6858}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1424234314000; file length: 6858
 doc saved: true; doc stamp: 0; doc size: 6858; committed: true
indexing info: indexed at 1424234314000 with size 6858
------------

	at com.intellij.psi.impl.source.PsiFileImpl.reportStubAstMismatch(PsiFileImpl.java:339)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:274)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:66)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:58)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:85)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:283)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.PsiFileImpl.calcStubAstBindings(PsiFileImpl.java:257)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:187)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:758)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:88)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:141)
	at com.goide.psi.impl.GoStubbedElementImpl.getText(GoStubbedElementImpl.java:59)
	at com.goide.GoAnnotator.getColor(GoAnnotator.java:184)
	at com.goide.GoAnnotator.highlightRefIfNeeded(GoAnnotator.java:86)
	at com.goide.GoAnnotator.annotate(GoAnnotator.java:54)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:159)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:340)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:205)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
2015-04-01 16:12:33,554 [ 259569]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.1.1  Build #IC-141.178.9 
2015-04-01 16:12:33,554 [ 259569]  ERROR - aemon.impl.PassExecutorService - JDK: 1.6.0_65 
2015-04-01 16:12:33,554 [ 259569]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-04-01 16:12:33,554 [ 259569]  ERROR - aemon.impl.PassExecutorService - Vendor: Apple Inc. 
2015-04-01 16:12:33,554 [ 259569]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2015-04-01 16:12:33,554 [ 259569]  ERROR - aemon.impl.PassExecutorService - Last Action: ShowLog 
2015-04-01 16:12:33,993 [ 260008]  ERROR - aemon.impl.PassExecutorService - Stub and PSI element type mismatch in pem.go: stub GoFunctionDeclarationStub, AST VAR_SPEC; Element(VAR_SPEC)
 file=GO_FILE, modStamp=0
 stub debugInfo=created in getStubTree(); with backReference
 document before=DocumentImpl[file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go]
latestIndexedStub=com.intellij.psi.stubs.StubTree@48f2a0a7
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go, content=DocumentContent{size=6858}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1424234314000; file length: 6858
 doc saved: true; doc stamp: 0; doc size: 6858; committed: true
indexing info: indexed at 1424234314000 with size 6858
------------
 
java.lang.AssertionError: Stub and PSI element type mismatch in pem.go: stub GoFunctionDeclarationStub, AST VAR_SPEC; Element(VAR_SPEC)
 file=GO_FILE, modStamp=0
 stub debugInfo=created in getStubTree(); with backReference
 document before=DocumentImpl[file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go]
latestIndexedStub=com.intellij.psi.stubs.StubTree@48f2a0a7
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go, content=DocumentContent{size=6858}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1424234314000; file length: 6858
 doc saved: true; doc stamp: 0; doc size: 6858; committed: true
indexing info: indexed at 1424234314000 with size 6858
------------

	at com.intellij.psi.impl.source.PsiFileImpl.reportStubAstMismatch(PsiFileImpl.java:339)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:274)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:66)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:58)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:85)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:283)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.PsiFileImpl.calcStubAstBindings(PsiFileImpl.java:257)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:187)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:758)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:88)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:141)
	at com.goide.psi.impl.GoStubbedElementImpl.getText(GoStubbedElementImpl.java:59)
	at com.goide.GoAnnotator.getColor(GoAnnotator.java:184)
	at com.goide.GoAnnotator.highlightRefIfNeeded(GoAnnotator.java:86)
	at com.goide.GoAnnotator.annotate(GoAnnotator.java:54)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:159)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:340)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:205)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
2015-04-01 16:12:33,993 [ 260008]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.1.1  Build #IC-141.178.9 
2015-04-01 16:12:33,993 [ 260008]  ERROR - aemon.impl.PassExecutorService - JDK: 1.6.0_65 
2015-04-01 16:12:33,993 [ 260008]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-04-01 16:12:33,993 [ 260008]  ERROR - aemon.impl.PassExecutorService - Vendor: Apple Inc. 
2015-04-01 16:12:33,993 [ 260008]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2015-04-01 16:12:33,993 [ 260008]  ERROR - aemon.impl.PassExecutorService - Last Action: ShowLog 
2015-04-01 16:12:33,993 [ 260008]  ERROR - aemon.impl.PassExecutorService - Stub and PSI element type mismatch in pem.go: stub GoFunctionDeclarationStub, AST VAR_SPEC; Element(VAR_SPEC)
 file=GO_FILE, modStamp=0
 stub debugInfo=created in getStubTree(); with backReference
 document before=DocumentImpl[file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go]
latestIndexedStub=com.intellij.psi.stubs.StubTree@48f2a0a7
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go, content=DocumentContent{size=6858}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1424234314000; file length: 6858
 doc saved: true; doc stamp: 0; doc size: 6858; committed: true
indexing info: indexed at 1424234314000 with size 6858
------------
 
java.lang.AssertionError: Stub and PSI element type mismatch in pem.go: stub GoFunctionDeclarationStub, AST VAR_SPEC; Element(VAR_SPEC)
 file=GO_FILE, modStamp=0
 stub debugInfo=created in getStubTree(); with backReference
 document before=DocumentImpl[file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go]
latestIndexedStub=com.intellij.psi.stubs.StubTree@48f2a0a7
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go, content=DocumentContent{size=6858}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1424234314000; file length: 6858
 doc saved: true; doc stamp: 0; doc size: 6858; committed: true
indexing info: indexed at 1424234314000 with size 6858
------------

	at com.intellij.psi.impl.source.PsiFileImpl.reportStubAstMismatch(PsiFileImpl.java:339)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:274)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:66)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:58)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:85)
	at com.intellij.psi.impl.source.PsiFileImpl$1.visitNode(PsiFileImpl.java:283)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:158)
	at com.intellij.psi.impl.source.PsiFileImpl.calcStubAstBindings(PsiFileImpl.java:257)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:187)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:758)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:88)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:141)
	at com.goide.psi.impl.GoStubbedElementImpl.getText(GoStubbedElementImpl.java:59)
	at com.goide.GoAnnotator.getColor(GoAnnotator.java:184)
	at com.goide.GoAnnotator.highlightRefIfNeeded(GoAnnotator.java:86)
	at com.goide.GoAnnotator.annotate(GoAnnotator.java:54)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:159)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:340)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:205)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
2015-04-01 16:12:33,994 [ 260009]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.1.1  Build #IC-141.178.9 
2015-04-01 16:12:33,994 [ 260009]  ERROR - aemon.impl.PassExecutorService - JDK: 1.6.0_65 
2015-04-01 16:12:33,994 [ 260009]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-04-01 16:12:33,994 [ 260009]  ERROR - aemon.impl.PassExecutorService - Vendor: Apple Inc. 
2015-04-01 16:12:33,994 [ 260009]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2015-04-01 16:12:33,994 [ 260009]  ERROR - aemon.impl.PassExecutorService - Last Action: ShowLog 
2015-04-01 16:12:34,473 [ 260488]  ERROR - aemon.impl.PassExecutorService - Stub and PSI element type mismatch in pem.go: stub GoFunctionDeclarationStub, AST VAR_SPEC; Element(VAR_SPEC)
 file=GO_FILE, modStamp=0
 stub debugInfo=created in getStubTree(); with backReference
 document before=DocumentImpl[file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go]
latestIndexedStub=com.intellij.psi.stubs.StubTree@5a33a0c4
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=SingleRootFileViewProvider{myVirtualFile=file:///usr/local/Cellar/go/1.4.2/libexec/src/encoding/pem/pem.go, content=DocumentContent{size=6858}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1424234314000; file length: 6858
 doc saved: true; doc stamp: 0; doc size: 6858; committed: true
indexing info: indexed at 1424234314000 with size 6858
------------

```

**Comment by ignatov** [comment] 2015-04-01 20:29
Reproduced, thanks.

**Closed** 2015-04-02 11:03 UTC
Labels: parser
