### ISSUE TITLE
not support vendor

### ISSUE THREAD

**Issue by freshcn** [go-lang-plugin-org/go-lang-idea-plugin#2105] opened 2015-12-16 04:02 UTC
Golang 1.5+ support vendor.But go-lang-idea-plugin not support vendor. Do you have plan to support vendor?

**Comment by dlsniper** [comment] 2015-12-16 08:23
Please see the discussion in
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1820, this
issue is a duplicate of that. Thank you.

**Comment by ignatov** [comment] 2015-12-17 14:58
Duplicates #1820

**Closed by ignatov** 2015-12-17 14:58 UTC
