### ISSUE TITLE
Inspection: uknown structure literal

### ISSUE THREAD

**Issue by ichekrygin** [go-lang-plugin-org/go-lang-idea-plugin#1479] opened 2015-03-24 19:22 UTC
type Foo struct {
    bar string
}

func main() {   
    bar := "qux";
    foo := &Foo{
        bar: "baz", // <-- inspection error: unknow field 'bar' structure literal 
    }
    fmt.Printf("Foo: %v, bar: %s", foo, bar)
}

**Comment by dlsniper** [comment] 2015-03-24 19:24
Plugin version? Duplicate of others?

**Comment by ichekrygin** [comment] 2015-03-24 19:57
plugin branch: v1.0.0-alpha0 on: b22e1f7
ingellij: IC-141.175.3
jre: 1.8.0_40-b25 amd64 
os: Linux 3.13.0-48-generic #80-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Comment by dlsniper** [comment] 2015-03-24 20:03
@zolotov isn't this a duplication of #1474 ? Also, it doesn't happen in c275c80bc1ec93236b8df47f37310519c853ceb7 which I was forced to use because of #1474

**Comment by zolotov** [comment] 2015-03-24 20:29
I don't see the connection between #1474 and this issue. But it's fixed in #1476

**Closed by zolotov** 2015-03-24 20:29 UTC
Labels: feedback required
