### ISSUE TITLE
Incorrect "unresolved" reference on method

### ISSUE THREAD

**Issue by deepfinesse** [go-lang-plugin-org/go-lang-idea-plugin#1756] opened 2015-07-17 02:42 UTC
Declaring a variable using ":=" with a typecast mucks up resolving method references.  This works:

type rankMask uint16
var ranks rankMask
ranks = 0xf
lowBit := ranks.findLowBit()    // this is a method on rankMask type

This does not work but is legal GO and builds and runs fine. findLowBit() is in red and says "unresolved"

type rankMask uint16
ranks := rankMask(0xf)
lowBit := ranks.findLowBit()

I'm using nightly build channel 5047 on WEBSTORM 10.0.4 on mac OS X yosemite. Go 1.4.2

**Comment by zolotov** [comment] 2015-07-17 10:00
> I'm using nightly build channel 5047 

Please specify particular plugin version

**Comment by dlsniper** [comment] 2015-07-17 10:11
Sorry, I think I was too quick to label this, I've just tested this code:

```go
package main

type rankMask uint16

func (d rankMask) findLowBit() int {
	return 1
}

func main() {
	var ranks rankMask
	ranks = 0xf
	lowBit := ranks.findLowBit()
	_ = lowBit
}
```

And it works fine. Which plugin version do you use? Can you share the actual code where this happens?

**Comment by deepfinesse** [comment] 2015-07-17 14:45
To dlsniper: yes your snippet works, per my bug report.  What does not work is when the ranks variable is declarer via := and a typecast.  Full code snippet that reproduces the problem is below.

To Zolotov: when I do Preferences->Plugins->Browse Repositories->Go it says "ver 0.9.397".  When I click Manage Repositories, it says: https://plugins.jetbrains.com/plugins/nightly/5047

package main

type rankMask uint16

func (d rankMask) findLowBit() int {
	return 1
}

func main() {
        // WHEN RANKS IS DECLARED THIS WAY, findLowBit() is red and says "Unresolved Reference"
	ranks := rankMask(0xf)
	lowBit := ranks.findLowBit()
	_ = lowBit
}

**Comment by dlsniper** [comment] 2015-07-17 14:48
@zolotov I think this is a duplicate of #1739, or at least looks like the same case (or #1740)

**Comment by deepfinesse** [comment] 2015-07-17 14:55
Yes, I agree.  Problem with variables declared via typecast.  Sorry to have filed a duplicate issue but at least it is another test case.  :)

**Comment by dlsniper** [comment] 2015-07-17 14:57
That's not a problem, it's quite a tricky one and it's hard to search if
something like that already exists, given all the combinations. Also, more
test cases are always good.

**Comment by dlsniper** [comment] 2015-07-20 16:00
@ignatov this looks fixed as well after https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/cfe0d88d83f5bdaec8cceef360390af02b5777bd Should I close it?

**Comment by ignatov** [comment] 2015-07-20 16:03
Duplicates #1739

**Closed by ignatov** 2015-07-20 16:03 UTC
Labels: resolving

**Comment by dlsniper** [comment] 2015-07-20 16:04
Ah, no, sorry, it's not fixed, I've took the wrong example. But at least it's a duplicate.
