### ISSUE TITLE
[1.0] Running tests from IDE doesn't work as GOPATH is not sent to the go tool

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1210] opened 2015-01-31 19:37 UTC
Hi,

I've tried running the tests for an app that I'm working on and unfortunately I'm not having success.
Everything else (autocompletion and so on) works ok.
Go Libraries from settings are configured to 'Global libraries' -> /home/florin/golang , the project is under $GOPATH/src/github.com/dlsniper/backend , I have GOPATH, in my OS, set to /home/florin/golang, go is in /usr/local/go1.4 and I get the following output from IDEA:

```
/usr/local/go1.4/bin/go test -v ./...
Testing started at 20:33 ...
backend.go:14:2: cannot find package "github.com/dlsniper/backend/config" in any of:
	/usr/local/go/src/github.com/dlsniper/backend/config (from $GOROOT)
	($GOPATH not set)
backend.go:15:2: cannot find package "github.com/dlsniper/backend/core" in any of:
	/usr/local/go/src/github.com/dlsniper/backend/core (from $GOROOT)
	($GOPATH not set)
backend.go:16:2: cannot find package "github.com/dlsniper/backend/server" in any of:
	/usr/local/go/src/github.com/dlsniper/backend/server (from $GOROOT)
	($GOPATH not set)
backend.go:17:2: cannot find package "github.com/dlsniper/backend/storage" in any of:
	/usr/local/go/src/github.com/dlsniper/backend/storage (from $GOROOT)
	($GOPATH not set)
backend.go:18:2: cannot find package "github.com/dlsniper/backend/storage/redis" in any of:
	/usr/local/go/src/github.com/dlsniper/backend/storage/redis (from $GOROOT)
	($GOPATH not set)
backend.go:20:2: cannot find package "github.com/yvasiyarov/gorelic" in any of:
	/usr/local/go/src/github.com/yvasiyarov/gorelic (from $GOROOT)
	($GOPATH not set)
core/account.go:10:2: cannot find package "github.com/dlsniper/backend/core/entity" in any of:
	/usr/local/go/src/github.com/dlsniper/backend/core/entity (from $GOROOT)
	($GOPATH not set)
core/core.go:10:2: cannot find package "gopkg.in/redis.v2" in any of:
	/usr/local/go/src/gopkg.in/redis.v2 (from $GOROOT)
	($GOPATH not set)
mysql/database.go:13:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/usr/local/go/src/github.com/go-sql-driver/mysql (from $GOROOT)
	($GOPATH not set)
mysql/database.go:14:2: cannot find package "github.com/jmoiron/sqlx" in any of:
	/usr/local/go/src/github.com/jmoiron/sqlx (from $GOROOT)
	($GOPATH not set)
server/account.go:13:2: cannot find package "github.com/gorilla/mux" in any of:
	/usr/local/go/src/github.com/gorilla/mux (from $GOROOT)
	($GOPATH not set)
server/account.go:16:2: cannot find package "github.com/dlsniper/backend/validator" in any of:
	/usr/local/go/src/github.com/dlsniper/backend/validator (from $GOROOT)
	($GOPATH not set)
validator/validator.go:8:2: cannot find package "github.com/asaskevich/govalidator" in any of:
	/usr/local/go/src/github.com/asaskevich/govalidator (from $GOROOT)
	($GOPATH not set)
```

**Comment by dlsniper** [comment] 2015-01-31 19:40
I'm using alpha#11 release

**Comment by JoeBruner** [comment] 2015-02-06 17:17
I'm having a similar problem with alpha#11

**Comment by JoeBruner** [comment] 2015-02-09 19:28
It would seem like this could be fixed with a simple change of line 74 https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/v1.0.0-alpha0/src/com/goide/runconfig/testing/GoTestRunningState.java#L71 
to

    final Map<String, String> goPathEnv = new HashMap<String, String>(); 
    goPathEnv.put("GOPATH", GoSdkUtil.retrieveGoPath(myModule));
    GeneralCommandLine installDependencies = new GeneralCommandLine().withEnvironment(goPathEnv);

and `GeneralCommandLine runTests` as well, but in my testing that didn't appear to work for some reason.  If I checked for GOPATH in the environment before changing to `withEnvironment()` it oddly wasn't there, but checking after setting `withEnvironment()` it was.  It still had the same problem, however, so not sure if we need to set the GOPATH to something else?

**Comment by dlsniper** [comment] 2015-02-09 19:38
@JoeBruner please submit a PR and either @ignatov or @zolotov will review it. From what I can tell, the change you suggest should be right. Thanks for investigating this!

**Comment by JoeBruner** [comment] 2015-02-09 19:43
Yah, I didn't make a PR because it didn't actually work :(

**Comment by dlsniper** [comment] 2015-02-09 19:47
as an idea, instead of running a run/build command, run ```go env``` and check the output, this way you should be able to understand what's happening there.

**Comment by JoeBruner** [comment] 2015-02-09 20:02
I think I might have an idea what might be wrong.  I don't think it's a GOPATH problem per say. Investigating...

**Comment by zolotov** [comment] 2015-02-09 20:04
It's not that simple, the problem is in compiler, not in running. It's jps module and it has quite non-trivial API. I'm aware of how to fix it, I just need a little time. Please let me fix it myself. I hope we'll see another contribution from you someday ;)

**Comment by zolotov** [comment] 2015-02-12 21:30
@JoeBruner it turned out that your fix was right actually, sorry for misinformation. It seems that 'go test' are starting with wrong arguments, I'll try to figure out what's wrong.

**Comment by JoeBruner** [comment] 2015-02-12 22:02
I did noticed that when I was running the test (Via right clicking on the method, Run "Test...") that the command line that it generated was something along the lines of `go test filename.go ....`.  According to http://stackoverflow.com/questions/14723229/go-test-cant-find-function-in-a-same-package that might be a problem.  I stopped looking into the problem, but maybe that's somewhere to start?

**Comment by zolotov** [comment] 2015-02-12 22:28
> According to http://stackoverflow.com/questions/14723229/go-test-cant-find-function-in-a-same-package that might be a problem.

That's right. File-based configuration (as well as single test configuration) doesn't work due to wrong arguments.
Package-based might not work because not really correct package-name validation.
Directory-based – don't know yet.

> I stopped looking into the problem, but maybe that's somewhere to start?

It would be great. There package 'com/goide/runconfig/testing' with all testing stuff. GoTestRunningState#fillCommandLineWithParameters fill parameters depending on configuration type, take a took at FILE type, that's the start.

**Closed** 2015-03-01 23:33 UTC
