### ISSUE TITLE
Reformat Code... is not consistent with go fmt

### ISSUE THREAD

**Issue by ichekrygin** [go-lang-plugin-org/go-lang-idea-plugin#1491] opened 2015-03-27 17:25 UTC
On branch v1.0.0-alpha0
As of: 6be350e

Repro steps: 
open any go file and Code/Reformat Code ...
Expected: code formatted consistently with go fmt output
Actual: something other... looks like plugin has defined and using format definition under "Settings/Editor/Code Style/Go", which is appears to be incomplete.

**Comment by dlsniper** [comment] 2015-03-27 17:27
Known bug. Closing as duplicate of existing issue.

**Closed by dlsniper** 2015-03-27 17:27 UTC
