### ISSUE TITLE
Variable declared within switch-case should be inaccessible outside switch-case

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1400] opened 2015-03-02 09:58 UTC
```
switch foo {
  case bar:
     x := anything{}
}

fmt.Println(x) // not flagged as error in IntelliJ
```

**Comment by dlsniper** [comment] 2015-03-02 10:07
This looks like a duplicate of #1269, see this comment : https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1269#issuecomment-75043641

**Comment by ignatov** [comment] 2015-04-26 13:22
Duplicates to #1269.

**Closed by ignatov** 2015-04-26 13:22 UTC
Labels: resolving
