### ISSUE TITLE
Debug: could not launch process: could not get thread count

### ISSUE THREAD

**Issue by richardpeng** [go-lang-plugin-org/go-lang-idea-plugin#2810] opened 2016-10-27 14:50 UTC
- Plugin version (or commit hash): 0.12.1799
- IDE name and version: IntelliJ IDEA 2016.2.5, Build #IU-162.2228.15, built on October 14, 2016
- Java version: 1.8.0_112-release-287-b2 x86_64
- OS name and version: macOS Sierra 10.12.1
- Command line tools version: 8.0.0.0.1.1472435881
- What are you trying to do?
  Debug and run an Application
- What would you expect to happen?
  The program to run and debugging to start
- What happens?

``` bash
could not launch process: could not get thread count
Process finished with exit code 1
```

This issue started when I updated to the latest version of macOS Sierra. I can still Run Applications using the IDE, just not Debug.

``` go
package main

import "fmt"

func main()  {
    fmt.Println("hello world")
}
```

**Comment by qianshangding** [comment] 2016-11-01 02:43
me too

**Comment by pkorobeinikov** [comment] 2016-11-01 05:14
This is a known delve issue: derekparker/delve/issues/645.

**Comment by oferitz** [comment] 2016-11-07 21:27
Seems like the delve issue ([derekparker/delve#645](https://github.com/derekparker/delve/issues/645)) was fixed.
Can we have it fixed here also?

**Comment by dlsniper** [comment] 2016-11-07 21:32
@oferitz it seems the issue is still open. Until it's merged into delve I don't think we should build our own delve. @zolotov / @ignatov what do you think/

**Comment by oferitz** [comment] 2016-11-07 21:47
@dlsniper you are right i was confused by [#577](https://github.com/derekparker/delve/issues/577).
it's probably good idea to wait.

**Comment by oferitz** [comment] 2016-12-19 20:35
Seems like the  [delve issue](https://github.com/derekparker/delve/pull/665) was fixed and merged.
Can we have it fixed here also?

**Closed** 2016-12-20 11:27 UTC
Labels: debugger, depends on 3rd party

**Comment by itzg** [comment] 2017-01-27 16:22
When is the planned release for this fix into the plugin and/or Gogland?

**Comment by zolotov** [comment] 2017-01-27 16:24
@itzg it was fixed in plugin [20th December](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/c77bd31b12227d5df1fc0cc79edf86248416d5fc) and in the Gogland in the very first EAP. What's the version you use?

**Comment by itzg** [comment] 2017-01-27 16:29
@zolotov I just installed Gogland to see if I had dirtied my IntelliJ install, so I'm running

```
Gogland (1.0 Preview) 1.0 EAP
Build #GO-163.10615.22, built on January 9, 2017
Gogland EAP User
Expiration date: April 9, 2017
JRE: 1.8.0_112-release-b460 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

Since I'm working on an open source project, here's the execution line and error:

```
/usr/local/Cellar/go/1.7.4_1/libexec/bin/go test -c -o "/private/var/folders/xf/96hzdx9n24s22r3_2wnw4_bxns4t3x/T/TestEleSession_HeartbeatSending in session_test.go (1)go" -gcflags "-N -l" github.com/racker/rackspace-monitoring-poller/poller
"/Applications/Gogland 1.0 EAP.app/Contents/bin/dlv" --listen=localhost:51220 --headless=true --api-version=2 exec "/private/var/folders/xf/96hzdx9n24s22r3_2wnw4_bxns4t3x/T/TestEleSession_HeartbeatSending in session_test.go (1)go" -- -test.v -test.run ^TestEleSession_HeartbeatSending$

could not launch process: could not get thread count

Process finished with exit code 1
```

**Comment by itzg** [comment] 2017-01-27 16:32
...and checking dlv version specifically:

```
~ "/Applications/Gogland 1.0 EAP.app/Contents/bin/dlv" version
Delve Debugger
Version: 0.11.0-alpha
Build:
```

**Comment by zolotov** [comment] 2017-01-27 16:32
@itzg likely it's the issue of delve, so it makes sense to help delve-maintainers to recreate this issue.

@dlsniper @ignatov could you look at it, please?

**Comment by itzg** [comment] 2017-01-27 17:22
FYI, this is definitely still a delve issue since I recreated their code signing cert and built latest from master with same results when running `dlv debug` directly. I'll find or report a new issue over there.

**Comment by zolotov** [comment] 2017-01-27 17:24
@itzg thank you for update and investigation

**Comment by linuxcer** [comment] 2018-02-02 01:06
# in your go project path, run follows command
```
go get github.com/derekparker/delve/cmd/dlv
cd src/github.com/derekparker/delve/cmd/dlv
go build 
mv ~/Library/Application\ Support/IdeaIC2016.2/Go/lib/dlv/mac/dlv ~/Library/Application\ Support/IdeaIC2016.2/Go/lib/dlv/mac/dlv_bak
cp dlv ~/Library/Application\ Support/IdeaIC2016.2/Go/lib/dlv/mac/
```
ok, it's works!

**Comment by dolphinsboy** [comment] 2019-01-02 09:48
@linuxcer It works for me, thank you!

IntelliJ IDEA 2017.3.4 (Ultimate Edition)
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3
