### ISSUE TITLE
Invalid inspection for `cap`

### ISSUE THREAD

**Issue by akaspin** [go-lang-plugin-org/go-lang-idea-plugin#2268] opened 2016-01-20 09:03 UTC
Following code is valid:
<img width="571" alt="screen shot 2016-01-20 at 12 01 29" src="https://cloud.githubusercontent.com/assets/140088/12444107/d21e16da-bf6d-11e5-85e1-6b0771ee0c1c.png">

**Comment by ignatov** [comment] 2016-01-20 09:51
@sjamesr If it occurs in type reference, please reassing to me.

**Comment by sjamesr** [comment] 2016-01-21 07:12
Looking at the inspection code and referencing the example in the screenshot, the problem is:

```java
    GoType baseType = getBaseType(exprType);
    if (baseType instanceof GoPointerType) {
      baseType = ((GoPointerType)baseType).getType();   // <--- for *ch, this returns a GoParType
      ...
```

What is the correct way to handle GoParType?

There's also a bug in the inspection where pointers to channels, arrays or slices would be permitted. The only valid pointer types for cap are pointers to arrays. This should be addressed with the following patch:

```patch
diff --git a/src/com/goide/highlighting/GoAnnotator.java b/src/com/goide/highlighting/GoAnnotator.java
index 7cae49b..d03a010 100644
--- a/src/com/goide/highlighting/GoAnnotator.java
+++ b/src/com/goide/highlighting/GoAnnotator.java
@@ -134,7 +134,13 @@ public class GoAnnotator implements Annotator {
     if (exprType == null) return;
     GoType baseType = getBaseType(exprType);
     if (baseType instanceof GoPointerType) {
+      // Only pointer to array is allowed in cap().
       baseType = ((GoPointerType)baseType).getType();
+      if (baseType instanceof GoArrayOrSliceType) {
+        if (((GoArrayOrSliceType)baseType).getExpression() != null) {
+          return;
+        }
+      }
     }
     if (baseType instanceof GoArrayOrSliceType || baseType instanceof GoChannelType) return;
     holder.createErrorAnnotation(first, "Invalid argument for cap");
```

**Comment by sjamesr** [comment] 2016-01-21 07:22
assigned to @ignatov for comment

**Comment by sjamesr** [comment] 2016-01-21 15:57
Another problem:

According to `getType`, the type of `*ch` is `(*((chan *bytes.Buffer)))`, not `chan *bytes.Buffer`. It seems as though par type handling is broken somewhere else too, I'm not sure where though.

**Closed** 2016-04-09 15:14 UTC
Labels: type inference
