### ISSUE TITLE
could you please add the command line project wizard support?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [go-lang-plugin-org/go-lang-idea-plugin#1840] opened 2015-09-01 07:12 UTC
as topic, could you please add the command line project wizard support?
thanks

**Comment by dlsniper** [comment] 2015-09-01 07:14
Hi, how should this feature work? Please provide more details. Thank you.

**Comment by ziyouchutuwenwu** [comment] 2015-09-01 07:22
if possible, add a button like "create new project"，
![aa](https://cloud.githubusercontent.com/assets/7458713/9598351/240ef6f0-50bd-11e5-9a49-a6e33716b706.png)

or inside this wizard，i can select golang project
![bb](https://cloud.githubusercontent.com/assets/7458713/9598358/3082d94c-50bd-11e5-8ad5-bdfe58b4217b.png)

**Comment by dlsniper** [comment] 2015-09-01 07:34
This was fixed by @ignatov in a previous nightly. Please try that release channel or wait for the next alpha release. If the issue is still not fixed, please reopen this. Thank you.

**Closed by dlsniper** 2015-09-01 07:34 UTC
Labels: feedback required

**Comment by ziyouchutuwenwu** [comment] 2015-09-01 07:38
thank you very much
