### ISSUE TITLE
Cannot import dependencies from vendor directory

### ISSUE THREAD

**Issue by imWildCat** [go-lang-plugin-org/go-lang-idea-plugin#2372] opened 2016-03-02 23:18 UTC
- Plugin version (or commit hash): 0.10.1164
- IDE name and version: Idea 15.0.4
- Java version:1.8.0_40
- OS name and version: OS X El Capitan
- Golang version: 1.6

- What are you trying to do?
Import dependencies from `vendor` directory

- What would you expect to happen?
Dependencies would be correctly imported and there is no error in the IDE.

- What happens?
![qq20160303-0](https://cloud.githubusercontent.com/assets/2396817/13479149/06f0211e-e110-11e5-99e7-673ddf363b1c.png)

```go
package main

import "fmt"
import "github.com/gin-gonic/gin"

func main() {
	fmt.Println("test")
	fmt.Println("dsd")

	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run()
}
```

**Comment by dlsniper** [comment] 2016-03-02 23:21
Hi @imWildCat, thank you for reporting (and respecting the format, awesome!).
Unfortunately I have to close this as a duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1820. Please follow that issue for updates on vendoring support.
Thank you (and sorry I can't give you better news).

**Closed by dlsniper** 2016-03-02 23:21 UTC

**Comment by imWildCat** [comment] 2016-03-02 23:22
@dvirsky Thanks
