### ISSUE TITLE
Debugging Support for gocheck

### ISSUE THREAD

**Issue by anidotnet** [go-lang-plugin-org/go-lang-idea-plugin#2364] opened 2016-02-28 05:53 UTC
- Plugin version (or commit hash): 0.10.1137
- IDE name and version: IntelliJ IDEA 15.0.4
- Java version: 1.8.0_65 (64-bit)
- OS name and version: Ubuntu 15.10 64bit

- What are you trying to do?
I am trying to debug gocheck test. Only run support is there, no debug support with delve.

- What would you expect to happen?
Adding debugging support for gocheck unit testing framework would be great to debug an application. In that way I don't have to run the whole application to debug a specific function.

**Comment by dlsniper** [comment] 2016-02-28 09:43
Closing as duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1855

**Closed by dlsniper** 2016-02-28 09:43 UTC
