### ISSUE TITLE
Check for unused variables

### ISSUE THREAD

**Issue by olegdunkan** [go-lang-plugin-org/go-lang-idea-plugin#1434] opened 2015-03-13 20:45 UTC
Try this and you will see warning  "Check for unused variables" for "ptr"
but all is ok, Go successfully compiles this.

type Some struct {
    field int
}

func main () {
    ptr := &Some{1}
    _ = (*ptr).field
}

**Comment by linniksa** [comment] 2015-03-13 21:16
in this code ptr var really unused

**Comment by mtoader** [comment] 2015-03-13 21:18
It is referred in the assignment `_ = (*ptr).field` which means it is used by go compiler definition.

**Comment by linniksa** [comment] 2015-03-13 21:31
yes and no, because code behaviour is not changed if i remove main body.
but for the intended behavior for unused vars inspection that code should be marked as a warning, not an error

**Comment by dlsniper** [comment] 2015-03-13 21:38
Go compiler will throw errors and won't compile the code if there are variables that are declared and initialized but not used to read from so I think the detection should be made better not the error level reduced.

**Comment by mtoader** [comment] 2015-03-13 21:52
Maybe two types of analysis might be in order ? 

1st level would be matching the compiler behavior, mostly because if it can't be compiled it will not run.

2nd level would be: opportunities for improvement by detecting no-op usages (as this one appears to be, etc)
 
1st one is relatively mechanical and straight forward to do and it should be done. The second one has the potential to be more complicated as you need to be able to reason about side effects and that make things complicated usually. 

I think this case should fall in the first type of analysis and it should pass. To make it match @linniksa 's suggestion i would add a new inspection with a completely different name and probably make it an optional warning.

**Closed** 2015-03-15 07:35 UTC
Labels: inspections

**Comment by ignatov** [comment] 2015-03-15 07:37
Please create another issue about more intelligent checks for unreachable code.
