### ISSUE TITLE
"Found several packages" error

### ISSUE THREAD

**Issue by carmandrew** [go-lang-plugin-org/go-lang-idea-plugin#2426] opened 2016-03-30 22:55 UTC
- Plugin version (or commit hash): 0.11.1197
- IDE name and version: Intellij IDEA Ultimate 2016.1
- OS name and version: mac os 10.11.3

I'm getting the error: "Found several packages [main, time] in 'path/to/appengine/sdk/1.9.30/.../goroot/src/time`"

When I got to that package, I see most of the files are of `package time` however one, genzabbrs.go, is `package main` with `// +build ignore`. For example, here's what `src/time/genzabbrs.go` looks like:

<img width="349" alt="genzabbrs_go_-_s0_-____code_s0_" src="https://cloud.githubusercontent.com/assets/630721/14160200/c7825372-f68f-11e5-88ca-de0d435bc24c.png">

It happens for other core library packages as well, like net/http.

**Comment by dlsniper** [comment] 2016-03-30 22:58
I've bumped into that one myself. The only way to fix it was to change remove the Go sdk, then create it again, set it to the project and module, and restart IDEA (or something very similar with those steps). I thought it was just a fluke as there was literally nothing in the logs.
As a question, I've noticed this when I've set the SDK for the project from the yellow tooltip. Have you done the same?

**Comment by carmandrew** [comment] 2016-03-30 23:15
Oh interesting. Actually, just restarting IDEA fixed it for me this time. I thought I tried that before, but I guess not. I think I probably did set the SDK from the tooltip, but don't remember for sure. I'm going to close the issue, since I can't reproduce it anymore and it's working.

**Comment by dlsniper** [comment] 2016-03-30 23:17
Hmm, I would rather keep this open and let Alexander close it. Maybe the logs could be useful to have?

**Closed** 2016-03-31 15:27 UTC

**Comment by ipcjk** [comment] 2016-04-11 12:16
Still happen to me
Version: 0.11.1281
Webstorm 2016.1
Mac 10.10.5

**Comment by zolotov** [comment] 2016-04-11 12:20
@ipcjk any steps to reproduce?

**Comment by dlsniper** [comment] 2016-04-11 12:20
@ipcjk please provide more details as this doesn't happen to me (I'm on the same version as you).
What have you done, how can we reproduce it? Also it could be useful to open a new issue to not spam @carmandrew :)

**Comment by ipcjk** [comment] 2016-04-11 12:40
To reproduce it: create a new go project with an empty file, select "Setup SDK" from that tooltip bubble, then go ahead and paste an easy application:

```
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Printf("Which month it is?%s\n", time.July.String())
}
```


Now build&run the application from the "Run"-Menu, then close and re-open the whole project and it will start bug you with warnings.

**Comment by dlsniper** [comment] 2016-04-11 12:44
@ipcjk can you please provide a screenshot for these warnings?

**Comment by zolotov** [comment] 2016-04-11 12:47
@ipcjk please attach .idea/ directory and *.iml files of that project.

**Comment by ipcjk** [comment] 2016-04-11 12:52
That project dir including .idea:
[untitled6.tar.gz](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/212961/untitled6.tar.gz)

Screenshots:
<img width="1280" alt="bildschirmfoto 2016-04-11 um 14 46 32" src="https://cloud.githubusercontent.com/assets/5488800/14427420/f6ad327a-fff4-11e5-8b0f-7010d1e04d8f.png">
<img width="1280" alt="bildschirmfoto 2016-04-11 um 14 46 25" src="https://cloud.githubusercontent.com/assets/5488800/14427426/01528ebe-fff5-11e5-8e97-12bf26375a1c.png">

**Comment by zolotov** [comment] 2016-04-11 13:39
@ipcjk still cannot recreate. please show me your Go SDK and Go Libraries settings

**Comment by ipcjk** [comment] 2016-04-11 13:48
Just defaults I guess?
<img width="989" alt="bildschirmfoto 2016-04-11 um 15 47 33" src="https://cloud.githubusercontent.com/assets/5488800/14429237/df3022f8-fffc-11e5-8d0a-81c103ace61d.png">
<img width="996" alt="bildschirmfoto 2016-04-11 um 15 44 26" src="https://cloud.githubusercontent.com/assets/5488800/14429238/df54b1e0-fffc-11e5-8dcb-93279890f19b.png">
<img width="1007" alt="bildschirmfoto 2016-04-11 um 15 44 19" src="https://cloud.githubusercontent.com/assets/5488800/14429239/df5b4e74-fffc-11e5-8c5a-a1877d37a513.png">

**Comment by zolotov** [comment] 2016-04-13 08:56
@ipcjk please try 0.11.1295 from nightly channel, should be fixed there

**Comment by ipcjk** [comment] 2016-04-13 09:24
Yes. Looks good!

**Comment by ndlang76** [comment] 2016-10-14 17:02
I am running into the same issue how would i go about getting 0.11.1295 from the nightly channel

**Comment by dlsniper** [comment] 2016-10-14 17:07
0.11.1295 is a very old version. Please upgrade your IDE to 2016.2 and it should receive a newer version of the plugin.
For using the nightly channel see the Readme. 
If you still have any issues, please open up a new issue with more details. 
Thank you.

**Comment by ndlang76** [comment] 2016-10-14 17:27
I oppend a new issue the number is 378

**Comment by ndlang76** [comment] 2016-10-14 17:29
Correction 2799

**Comment by prydin** [comment] 2017-01-10 14:46
I'm still getting this error. Here's my IntelliJ version:
IntelliJ IDEA 2016.3.2
Build #IC-163.10154.41, built on December 21, 2016
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Plugin version:  0.13.1924

MacOS 10.12.1

<img width="1264" alt="screen shot 2017-01-10 at 9 36 32 am" src="https://cloud.githubusercontent.com/assets/5239535/21810408/a7f1e82c-d719-11e6-991e-31db01f1b4b3.png">

**Comment by metalwood** [comment] 2017-02-09 03:10
Still error, "found several packages","unresolved reference"...
Idea 3.2/3.2 Community/Ultimate
Go plugin 0.13.1924
macOS 10.11

**Comment by metalwood** [comment] 2017-02-09 03:20
rm .idea and reopen project, it fixed. @prydin

**Comment by aniketdivekar** [comment] 2022-05-08 11:04
It happened for me when I was on go version 1.16 and updated to 1.18 by downloading the package and installing in background while IDE was open. I restarted it and solved for me, but had to read [this comment](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2426#issuecomment-203677955) to realise I can try restarting.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/1047471/167293245-6351bee5-eb48-4f4b-a655-d768c07beea3.png">

Just make sure GOROOT is shown as expected in Preferences. It was showing 1.16 before restarting the IDE

**Comment by SummitXY** [comment] 2022-06-21 10:30
> rm .idea and reopen project, it fixed. @prydin

After deleting .idea, my Golang became this one with yellow backgroud.
![image](https://user-images.githubusercontent.com/22277899/174778891-e67a92c3-8f8e-41a9-84d1-e52bbdef7e64.png)

**Comment by bigsheeper** [comment] 2023-04-08 09:22
I tried to rm .idea and reopen project, but didn't work.
However, upgrade Goland works for me.
