### ISSUE TITLE
"func" type not supported

### ISSUE THREAD

**Issue by pierrre** [go-lang-plugin-org/go-lang-idea-plugin#1740] opened 2015-07-11 18:36 UTC
IDEA version: 14.1.4
OS version: 4.0.7-2-ARCH 1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64 GNU/Linux (Xfce desktop env)
Java version: java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
Go IntelliJ plugin version: 0.9.388
Go version: 1.4.2

In my project, I have a "func" type:
https://github.com/pierrre/imageserver/blob/master/server.go#L10
```go
// ServerFunc is a Server func.
type ServerFunc func(params Params) (*Image, error)

// Get implements Server.
func (f ServerFunc) Get(params Params) (*Image, error) {
	return f(params)
}
```
It implements:
``` go
// Server represents an Image server
type Server interface {
	Get(Params) (*Image, error)
}
```

But it's not detected as a `Server`.
See https://github.com/pierrre/imageserver/blob/master/server_test.go#L18 .
``` go
	server := ServerFunc(func(params Params) (*Image, error) {
		called = true
		return testdata.Medium, nil
	})
	server.Get(Params{})
```
IntelliJ says: "Unresolved reference 'Get'"
`Get` is highlighted in red.
"ctrl+click" doesn't go to definition.
Autocompletion suggests my `server` variable is an `*Image`...

**Comment by dlsniper** [comment] 2015-07-11 18:49
Hi, thanks for reporting. I think this is a duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1739, no? I'll close this for now, please feel free to reopen it if it's not.

**Comment by pierrre** [comment] 2015-07-11 18:54
I don't know.
In my code, I use a "func type".
In #1739, it's a string type.

And autocompletion suggests my `server` variable is an `*Image`.
It's weird...

**Comment by dlsniper** [comment] 2015-07-11 19:46
The underlying issue is the same, it seems that type casts are not handled by the plugin, regardless of what's being casted to what. @zolotov please correct me if I'm wrong.

**Comment by pierrre** [comment] 2015-07-11 19:48
OK I understand.
Sorry for the duplicated issue.

**Comment by dlsniper** [comment] 2015-07-11 19:49
Np, it's not immediately obvious. Plus, more examples the better ;)

**Comment by zolotov** [comment] 2015-07-12 02:41
> The underlying issue is the same, it seems that type casts are not handled by the plugin, regardless of what's being casted to what.

We have no idea what's the underlying issue :) So I reopen for a while

**Comment by JakeWarner** [comment] 2015-08-13 00:56
Can confirm this issue on the v0.9.402 alpha build.

**Closed** 2015-09-07 12:53 UTC
Labels: resolving
