### ISSUE TITLE
Unable to exclude folder from GOPATH global library content

### ISSUE THREAD

**Issue by StanislavBelyakov** [go-lang-plugin-org/go-lang-idea-plugin#2743] opened 2016-08-16 18:15 UTC
- Plugin version 0.12.1795
- IDEA 2016.2.1
- Java 1.8
- Mac OS X 10.11.6

I'm trying to exclude a folder from external libraries content via "File -> Project Structure... -> Libraries -> Exclude " option. Once folder is excluded, IDEA updates `.idea/libraries/GOPATH__project_name_.xml` file, so it looks like this:
```
<component name="libraryTable">
  <library name="GOPATH &lt;project-name&gt;">
    <CLASSES>
      <root url="file://$PROJECT_DIR$/../../../golang.org" />
      <root url="file://$PROJECT_DIR$/../../../bitbucket.org" />
      <root url="file://$PROJECT_DIR$/../../../gopkg.in" />
      <root url="file://$PROJECT_DIR$/../.." />
    </CLASSES>
    <JAVADOC />
    <SOURCES>
      <root url="file://$PROJECT_DIR$/../../../golang.org" />
      <root url="file://$PROJECT_DIR$/../../../bitbucket.org" />
      <root url="file://$PROJECT_DIR$/../../../gopkg.in" />
      <root url="file://$PROJECT_DIR$/../.." />
    </SOURCES>
    <excluded>
      <root url="file://$PROJECT_DIR$" />
      <root url="file://$PROJECT_DIR$/../excluded-folder" />
    </excluded>
  </library>
</component>
```

Everything works fine, until I restart the application. Once restarted, application ignores the content of the file, so the folder becomes included again. 

If I deselect "Use GOPATH" (see pic below), and add project external libraries manually, then "exclude" feature works fine for such library:

![go_libraries](https://cloud.githubusercontent.com/assets/9965438/17710215/9a56cc5a-63ec-11e6-8a00-714a40ae149b.png)

However, manually added library cannot be recognized by plugin, so the workaround doesn't work.

**Comment by zolotov** [comment] 2016-08-16 19:21
Why do you want to exclude something? You cannot exclude anything from gopath. If you have a package in gopath directory, you cannot tell gobuild that some particular directory should be excluded. The same in ide

**Comment by zolotov** [comment] 2016-08-16 19:22
Library tables are not supposed to be edited manually too

**Comment by StanislavBelyakov** [comment] 2016-08-16 19:38
I'm not trying to somehow affect go-related workflow. Instead, I just want to exclude a folder from indexing by IDEA. I assume it should be working fine, since UI allows to do that:
![dialog](https://cloud.githubusercontent.com/assets/9965438/17713134/a151eb04-63f9-11e6-90c0-669b1e1a0083.png)

Plus, it actually works until IDE restart.

**Comment by zolotov** [comment] 2016-08-16 19:50
You didn't answer.

In cannot be edited in other ides  and it won't be edited in idea in future.

**Comment by StanislavBelyakov** [comment] 2016-08-16 20:23
The reason is in the following:
Both `my-project` and `excluded-project` are separate repos, and each contains JS code somewhere within. For some cases, IDEA cannot recognize the actual source of the imported JS module, because `excluded-project` has a file with the similar or the same path + name (I'm referring to ES6 import feature), so it becomes annoying to use autocompletion, "go to source", etc.

I know this case sounds pretty minor, but, it could've been fixed easily by the option I was talking about. Since this is an expected behavior and won't be supported in a future, I'll have to look for the different workaround.

**Comment by zolotov** [comment] 2016-08-16 21:10
I see, I'll ask my colleagues on JS part whether it can be fixed there

**Comment by zolotov** [comment] 2016-08-23 10:09
@StanislavBelyakov hey, could you please give me content of js files to recreate the problem? Or samples projects which I can put in my GOPATH and get incorrect behaviour on JavaScript imports. Thanks

**Comment by StanislavBelyakov** [comment] 2016-08-23 17:26
Here are the sample projects, which should be located in the same GOPATH subdirectory:
[main-project.zip](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/433113/main-project.zip)
[unused-project.zip](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/433114/unused-project.zip)

It looks like I'm unable to reproduce the behavior now. 
Previously, for example, attempt to open definition of the `{test}` by clicking on import section inside `main-project/js/entry/test.js` sometimes could redirect me to `unused-project/js/foo/bar/lib`, instead of `main-project/js/foo/bar/lib.js`. Now the reference cannot be resolved, which is probably correct, because I'm not using either a relative path or a path relative to `node_modules` folder. Strange that it worked though.

**Comment by zolotov** [comment] 2016-08-24 16:02
Cannot reproduce either. So I'm closing the issue right now. Feel free to ping me if you face the problem again.

**Closed by zolotov** 2016-08-24 16:02 UTC
Labels: depends on IntelliJ platform
