### ISSUE TITLE
Good code red:  "Duplicate function name" for build constraint

### ISSUE THREAD

**Issue by mmindenhall** [go-lang-plugin-org/go-lang-idea-plugin#1762] opened 2015-07-20 20:46 UTC
Hello,

I have defined files with platform-specific code for obtaining a unique ID (in this case, the serial number of the device) from the underlying platform.  I have defined the following files:

```
├── conf
│   ├── unique_id_darwin.go
│   └── unique_id_linux.go
```

Within each of those two files, I have defined a function as follows:

```go
func getSystemUniqueId() string {
	...
}
```

In both files, the function name gets the red squiggly underline treatment with the "Duplicate function name" message.  The code is valid, as only one of these two implementations could possibly be included in a build (see Build Constraints section of [go/build](http://golang.org/pkg/go/build/) package).

Thanks!

IDEA version: 14.1.4 (141.1532)
OS version: OS X 10.10.4
JDK version: 1.6.0_65 (Apple JDK)
plugin version: 0.9.371

**Comment by dlsniper** [comment] 2015-07-20 20:48
Hi, what plugin version are you using? What configuration do you have for the build target? Have you specified any architecture / custom tags? Thank you.

**Comment by mmindenhall** [comment] 2015-07-20 20:58
Sorry about that...I edited the issue to include versions.  Within the IDE, I'm using the defaults for OS & Arch, and no custom flags.

**Comment by dlsniper** [comment] 2015-07-20 21:01
Great. Please try the nightly channel which should contain a fix for this issue or wait for the next alpha release (which should be here soon). If it still happens, please let us know. I'll close this for now as it seems it's a duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1721 Thank you.

**Comment by dlsniper** [comment] 2015-07-20 21:01
I've forgot to mention that if the issue still happens, please reopen this. Thank you.

**Closed by dlsniper** 2015-07-20 21:01 UTC
Labels: feedback required
