### ISSUE TITLE
auto remove useless import

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#2568] opened 2016-06-15 14:14 UTC
If the plugin finds that there is an useless import, it can add a '//' at the begin of that line immediately.
If the plugin finds it looks like a import is missing, it can try the comment out imports first,then guess the full import path.
With this method, the user can make the decide about which full import path to use once and reuse that decide again.

**Comment by zolotov** [comment] 2016-06-15 14:16
> With this method, the user can make the decide about which full import path to use once and reuse that decide again.

now you can import package once and plugin won't suggest to import the same package with different import path, what's the difference?

**Comment by bronze1man** [comment] 2016-06-15 14:43
You import package, the plugin will suggest to import with different path.
You choose one,
You remove this path.
You import it again,the plugin will suggest to import with different path again.

With trying the comment out imports first, it will avoid this kind of repeat work for user.

**Comment by zolotov** [comment] 2016-06-15 14:47
Why did you remove it in the first place?

> the plugin will suggest to import with different path.

you can avoid suggesting several paths by excluding unneeded packages from GOPATH or via settings (see L&G | Go | Auto Import)

**Comment by bronze1man** [comment] 2016-06-15 14:53
Yes, I can also delete packages with the same name or rename them.
But you suggest need the user to understand more and do something more, which is a worse user experience.

**Comment by zolotov** [comment] 2016-06-15 14:55
I doubt that special handling of commented imports would make it easier to understand what's happening

**Comment by bronze1man** [comment] 2016-06-15 15:02
I think the user do not need to understand what's happening.
His program just run correctly.
I do not care what's happening when I use my tool to auto comment out useless import path.The program just run correctly without user notice.(I had wrote a tool called `kmg gorun` which can auto comment out useless import path after a failed go install,and run go install again)

**Comment by dlsniper** [comment] 2016-06-15 15:05
I've said it on Gitter and I say it now, you can bind a shortcut to `goimports` action and use that to save the file AND run goimports which cleans up the imports from the file until the plugin gets support for doing the import cleanup automatically.

**Comment by bronze1man** [comment] 2016-06-15 15:08
@dlsniper 
Thanks, I just want to know whether this method works for everybody before I start working on it.

**Comment by dlsniper** [comment] 2016-06-15 15:13
Imho if you plan to work on it, it's better to remove the import completely if not used rather than comment it out. That's what most of the gophers are used to, having comments for unused imports is terrible.

**Comment by bronze1man** [comment] 2016-06-15 15:17
@dlsniper 
Thanks. I got it.The situation which I mentioned should happened rarely.

**Comment by dlsniper** [comment] 2016-06-18 18:23
I'll close this as duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2568.

**Closed by dlsniper** 2016-06-18 18:23 UTC
