### ISSUE TITLE
1.0.0: Struct literal is reported as error if declared inside a for loop

### ISSUE THREAD

**Issue by horkhe** [go-lang-plugin-org/go-lang-idea-plugin#1477] opened 2015-03-23 19:55 UTC
```Go
type A struct {}

func Test1() *A {
	a := &A{} // Ok
	if true {
		a = &A{} // Ok
	}
	for {
		a = &A{} // But, error reported: '!=', ... '|', or '}' expected but got '{'
	}
	return a
}
```

**Comment by dlsniper** [comment] 2015-03-23 20:05
Duplicate of #1474

**Comment by dlsniper** [comment] 2015-03-23 20:05
(I think it's a duplicate, at least :D)

**Closed by dlsniper** 2015-03-23 20:05 UTC
Labels: parser
