### ISSUE TITLE
[1.0] alpha 58 struct fields dont autocomplete

### ISSUE THREAD

**Issue by sclasen** [go-lang-plugin-org/go-lang-idea-plugin#1286] opened 2015-02-10 21:58 UTC
the 0.9 series worked (for me) whereas the 1.0 doesnt in the following kind of scenario

```go

type Foo struct{
   Bar string
   Baz int
}

foo := &Foo{
   //cursor here, activate autocomplete, nada.
}


```

**Comment by dlsniper** [comment] 2015-02-10 22:00
Thanks for reporting, however it's a duplicate of #1162.

**Closed by dlsniper** 2015-02-10 22:00 UTC
