### ISSUE TITLE
Printf/Logf placeholder handler inspection can't handle %+v

### ISSUE THREAD

**Issue by gabrielf** [go-lang-plugin-org/go-lang-idea-plugin#2318] opened 2016-02-01 11:54 UTC
Goplugin version: 0.10.1097
IntelliJ-version: 15.0.3

This code gives an inspection warning even though it's correct. It seems the placeholder %+v is not handled the way %#v is:

```go
func Foo() string {
	val := "something"
	return fmt.Sprintf("%+v", val) // This line is caught in the inspection as missing placeholder
}
```

As seen in this screenshot.

![image](https://cloud.githubusercontent.com/assets/137649/12716630/4c5bad4a-c8e2-11e5-8a70-882eb96c7e38.png)

**Comment by dlsniper** [comment] 2016-02-01 12:38
I'll close this as a duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2194 Thank you for reporting.

**Closed by dlsniper** 2016-02-01 12:38 UTC
Labels: bug, inspections
