### ISSUE TITLE
example of go vet warning not showing up

### ISSUE THREAD

**Issue by veqryn** [go-lang-plugin-org/go-lang-idea-plugin#2221] opened 2016-01-09 08:01 UTC
As per https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2220 here is an example with the error message: range variable v captured by func literal

```
package main

import "fmt"

// you think this will print "w x y z" but you usually get "z z z z"
func main() {

	values := []string{"w", "x", "y", "z"}

	done := make(chan bool)

	// bad way of doing it, because v gets changed while iterating
	for _, v := range values {
		go func() {
			// go vet will warn about the following line:
			fmt.Println(v)
			done <- true
		}()
	}

	// wait for all goroutines to complete before exiting
	for _ = range values {
		<-done
	}
}
```

**Comment by ignatov** [comment] 2016-01-09 08:41
Thanks for the example, but I'm closing the issue as a duplicate of #2220.

**Closed by ignatov** 2016-01-09 08:41 UTC

**Comment by veqryn** [comment] 2016-01-09 11:34
@ignatov I was asked to open this as a new ticket by @dlsniper 
```
easy way to recreate this is to write a closure that captures a non-final variable
Can you please open up a new issue with this and a code sample to reproduce the issue? I'm not sure I understand it. Thank you.
```
