### ISSUE TITLE
Webstorm version mismatch

### ISSUE THREAD

**Issue by EtienneBruines** [go-lang-plugin-org/go-lang-idea-plugin#2565] opened 2016-06-15 08:22 UTC
Upon trying to install the Go plugin (downloading works, installing results in this error in the terminal):

```
WARN: Can't load Go: until build 162.844 does not match WS-162.844.4
```

I am running `Webstorm 2016.2 EAP (162.844.4)` on `Debian Testing` with `Linux 4.3.0`.

**Comment by EtienneBruines** [comment] 2016-06-15 08:24
Apparently this behavior matches that described in https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2562 and shown in video https://youtrack.jetbrains.com/issue/IDEA-157452. 

I am not sure if this is something `go-lang-plugin-org` should fix, or something that `jetbrains` should fix.

**Comment by dlsniper** [comment] 2016-06-15 08:24
Could this be a duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2562?

**Comment by dlsniper** [comment] 2016-06-15 08:24
Ok, closing this then

**Closed by dlsniper** 2016-06-15 08:24 UTC

**Comment by zolotov** [comment] 2016-06-15 16:10
should be fixed in the next eap
