### ISSUE TITLE
Run tests with debugger

### ISSUE THREAD

**Issue by antonikonovalov** [go-lang-plugin-org/go-lang-idea-plugin#1903] opened 2015-10-06 08:00 UTC
Now we can run only application with debuuger. Can you add `run test with debugger` also?

**Comment by dlsniper** [comment] 2015-10-06 08:02
Closing this as a duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1855

**Closed by dlsniper** 2015-10-06 08:02 UTC
