### ISSUE TITLE
Search term "tab" does not navigate to Go tab in IDE settings

### ISSUE THREAD

**Issue by HouzuoGuo** [go-lang-plugin-org/go-lang-idea-plugin#2404] opened 2016-03-21 08:05 UTC
- Plugin version (or commit hash): 0.11.1197
- IDE name and version: 2016.1
- Java version: OpenJDK 1.8
- OS name and version: openSUSE tumbleweed

- What are you trying to do?
Look for term "tab" in IDE settings

- What would you expect to happen?
Code Style -> Go to appear as a match

- What happens?
Code Style -> Go is not a match

This is a minor issue, if I knew more about IDEA plugin development I would have sent a PR :)

**Comment by dlsniper** [comment] 2016-03-21 08:08
Hi, thanks for reporting. I think this could be flagged as a duplicate of: [Make plugin settings searchable in IDEA](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2209).

**Closed by dlsniper** 2016-03-21 08:08 UTC

**Comment by HouzuoGuo** [comment] 2016-03-21 08:13
thank you.
