### ISSUE TITLE
golang plugin incompatible with latest IntelliJ 2016.1.1 bug fix release

### ISSUE THREAD

**Issue by Ravenwater** [go-lang-plugin-org/go-lang-idea-plugin#2438] opened 2016-04-04 12:31 UTC
- Plugin version (or commit hash): Go v.0.11.1197
- IDE name and version: 2016.1.1 145.597
- Java version: 1.8.0_73
- OS name and version:  Windows 10

- What are you trying to do? golang dev

- What would you expect to happen? golang plugin to be operational

- What happens? Golang plugin is not recognized

Your issue description goes here.
Please be as detailed as possible

any go project will have this issue

![image](https://cloud.githubusercontent.com/assets/466641/14247868/2e79217a-fa3f-11e5-9165-cc534411d387.png)

[idea-log.zip](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/202381/idea-log.zip)

**Comment by dlsniper** [comment] 2016-04-04 12:32
Duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2428 but thanks for the logs.

**Closed by dlsniper** 2016-04-04 12:32 UTC

**Comment by dlsniper** [comment] 2016-04-04 12:39
@zolotov check the last start of the IDE, that looks strange to me

```
[...]
2016-04-04 08:16:58,599 [  17472]   INFO - llij.ide.plugins.PluginManager - Plugin 'Go' can't be loaded because: Plugin since-build or until-build don't match this product's build number
[...]
2016-04-04 08:16:58,964 [  17837]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: Go (0.11.1197)
[...]
2016-04-04 08:21:13,204 [ 272077]   INFO - Settings.impl.PluginDownloader - Plugin ro.redeul.google.go: current version (max) 0.11.1197
```

**Comment by Ravenwater** [comment] 2016-04-04 12:45
After restart, all looks good:

2016-04-04 08:35:30,698 [   2795]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Go (0.11.1197), LiveEdit (145.9), NodeJS (145.249), Scala (3.0.1)
