### ISSUE TITLE
No completion suggestions shown for methods on structs defined in *_test.go files

### ISSUE THREAD

**Issue by mdwhatcott** [go-lang-plugin-org/go-lang-idea-plugin#2420] opened 2016-03-29 17:38 UTC
- Plugin version (or commit hash): `0.11.1197`
- IDE name and version:

```
IntelliJ IDEA 2016.1
Build #IC-145.258, built on March 17, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

- OS name and version:  `Mac OS 10.10.5`

- What are you trying to do? 

**Having defined a struct with a few methods all within a *_test.go file I'd like to be able to call the methods from within that test file because they have useful behavior. However, when typing "." (or ctrl+space) the methods are not contained in the suggestion list that appears.**

- What would you expect to happen? 

**The methods should be found in the suggestion list.**

### Code Sample (screenshot provided below):

```go
package engine

import "testing"

type Thing struct {

}

func (this *Thing) Method() {

}

func TestSomething(t *testing.T) {
	t := new(Thing)
	t. // no suggestions
}

```

### Screenshot:

![screen shot 2016-03-29 at 11 33 39 am](https://cloud.githubusercontent.com/assets/202910/14117657/d28c7c7c-f5a2-11e5-8a11-44db0066c4ca.png)

**Comment by kaedys** [comment] 2016-03-29 20:21
Duplicate of #2303?

**Comment by zolotov** [comment] 2016-03-29 22:21
@kaedys indeed, thanks

**Closed by zolotov** 2016-03-29 22:21 UTC
