### ISSUE TITLE
Unresolved method

### ISSUE THREAD

**Issue by zolotov** [go-lang-plugin-org/go-lang-idea-plugin#2057] opened 2015-12-01 13:46 UTC
```go
package main

import "fmt"

type ConnStatus interface {
	Status() int32
	Error() error
}

func Bind() <-chan ConnStatus {
	ch := make(chan ConnStatus, 1)
	return ch
}

func main() {
	a := Bind()
	for c := range a {
		fmt.Println("Connection status:", c.Status()) //Status() is unresolved
	}
}
```

**Comment by sjamesr** [comment] 2015-12-06 20:08
Looks like the problem is that resolving `c` yields null. Looking closer, we have:
```
at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:145)
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
at com.goide.psi.impl.GoReference.multiResolve(GoReference.java:102)
at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
```

`ResolveCache` line 145 is:

```java
PsiElement element = result instanceof ResolveResult ? 
                                          ((ResolveResult)result).getElement() : null;
```

`result` is an array of one `ResolveResult`, whose element is the lhs of `c := range a`, which looks correct. Of course the `instanceof` test fails and null is returned. This doesn't seem right, maybe GoReference.multiResolve is calling the wrong resolve method?

**Comment by sjamesr** [comment] 2015-12-06 20:35
In `GoPsiImplUtil.processRangeClause` line 650, we have

```java
      GoType type = last.getGoType(context);
```

In this case, `last` refers to `a` in `c := range a`. `type` resolves to `ConnStatus`, whereas it should probably resolve to `<-chan ConnStatus`, right?

**Closed** 2015-12-19 14:07 UTC
Labels: resolving
