### ISSUE TITLE
Assignment count mismatch in range

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1457] opened 2015-03-19 14:20 UTC
In the code:
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	var tick = 0
	for range time.NewTicker(1 * time.Second).C { // Assignment count mismatch: 0 = 1
		fmt.Println("Tick")
		tick++
		if tick > 3 {
			break
		}
	}
}
```
Line ```for range...``` reports error "Assignment count mismatch: 0 = 1".

IDEA IU-141.104.1
Plugin 0.9.201

**Comment by dlsniper** [comment] 2015-03-19 14:27
Not sure if it's a duplicate ofhttps://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1451 or not

**Closed** 2015-03-26 01:20 UTC
