### ISSUE TITLE
Show constant values

### ISSUE THREAD

**Issue by saturn4er** [go-lang-plugin-org/go-lang-idea-plugin#2070] opened 2015-12-06 12:53 UTC
If it is possible, can you implement hint with value of const on mouse hover.

**Comment by dlsniper** [comment] 2015-12-06 13:03
Closing as duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1422

**Closed by dlsniper** 2015-12-06 13:03 UTC
