### ISSUE TITLE
Debugging not working as expected

### ISSUE THREAD

**Issue by itachi3** [go-lang-plugin-org/go-lang-idea-plugin#1998] opened 2015-11-15 12:40 UTC
Using Intellij 14.1.4

Have installed Go plugin (https://plugins.jetbrains.com/plugins/nightly/5047). While debugging the program stops at breakpoint but unable to evaluate the expression. As an example wrote a simple web server and a POST call. If i try to print the HTTP Headers to console it works, but not via evaluate expression.

<img width="1228" alt="screen shot 2015-11-15 at 6 09 58 pm" src="https://cloud.githubusercontent.com/assets/10880793/11168764/22659f7e-8bc4-11e5-8845-a07812342f81.png">

**Comment by dlsniper** [comment] 2015-11-15 12:53
I'll have to have a look at it but I think delve might not support this yes, see https://github.com/derekparker/delve/issues/119

**Comment by dlsniper** [comment] 2015-11-15 13:24
Closing this as a duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1892 (and the delve one I guess)

**Closed by dlsniper** 2015-11-15 13:24 UTC
Labels: depends on 3rd party

**Comment by itachi3** [comment] 2015-11-15 13:38
@dlsniper Thank you will watch over in delve tracker
